Systems-Modeling/SysML-v2-Pilot-Implementation

- org.omg.sysml/syntax-gen/org/omg/sysml/lang/sysml/impl/ConnectorImpl.java
- sysml.library/Kernel Library/BaseFunctions.kerml
- sysml.library/Kernel Library/Objects.kerml
- sysml.library/Kernel Library/Occurrences.kerml
Also includes an update to resolve ST6RI-289 (The end multiplicities of SelfLink should be 1..1 and unique).
> ST6RI-292 Asymmetric HappensBefore, reflexive HappensDuring, remove redundant self subsets

- org.omg.sysml.interactive/src/org/omg/sysml/interactive/SysMLInteractive.java
- org.omg.sysml.plantuml/META-INF/MANIFEST.MF
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/SysML2PlantUMLStyle.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/SysML2PlantUMLText.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VAction.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VCompartment.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VComposite.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VDefault.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VMixed.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VStateMachine.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VStructure.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/Visitor.java
See https://openmbee.atlassian.net/browse/ST6RI-299 for details. 
**Notice that you need to update PlantUML to version 1.2020.14.himi4**
> ST6RI-299: Properly show exhibit state usages in PlantUML visualization

- sysml.library/Domain Libraries/Quantities and Units/ISQ.sysml
- sysml.library/Domain Libraries/Quantities and Units/ISQAcoustics.sysml
- sysml.library/Domain Libraries/Quantities and Units/ISQAtomicNuclear.sysml
- sysml.library/Domain Libraries/Quantities and Units/ISQCharacteristicNumbers.sysml
- sysml.library/Domain Libraries/Quantities and Units/ISQChemistryMolecular.sysml
- sysml.library/Domain Libraries/Quantities and Units/ISQElectromagnetism.sysml
- sysml.library/Domain Libraries/Quantities and Units/ISQLight.sysml
- sysml.library/Domain Libraries/Quantities and Units/ISQMechanics.sysml
- sysml.library/Domain Libraries/Quantities and Units/ISQSpaceTime.sysml
- sysml.library/Domain Libraries/Quantities and Units/ISQThermodynamics.sysml
- sysml.library/Domain Libraries/Quantities and Units/SI.sysml
- sysml.library/Domain Libraries/Quantities and Units/UnitsAndScales.sysml
Tested in the latest Eclipse pilot implementation tool. Verified that the updated libraries parse successfully without warnings, and do not introduce any errors or new warnings in the SysML examples and validation cases.
> ST6RI-297 Update with ISO 80000 parts 8 and 11 complete

- .travis.yml
It also tests pull request integration.
> ST6RI-317: Automate Maven Build with Travis-CI

- org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/AllKerMLXpectTests.java
- org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/imports/recursive/HumanId_Import_Valid1.kerml.xt
- org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/imports/recursive/HumanId_Import_Valid2.kerml.xt
- org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/imports/recursive/Import_Recursive1.kerml.xt
- org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/imports/recursive/Import_Recursive1_scope_otherfile.kerml.xt
- org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/imports/recursive/Import_Recursive2.kerml.xt
- org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/imports/recursive/Import_Recursive2_scope_otherfile.kerml.xt
- org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/imports/recursive/Import_Recursive3.kerml.xt
- org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/imports/recursive/Import_Recursive3_scope_otherfile.kerml.xt
- org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/imports/recursive/Import_Recursive4.kerml.xt
- org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/imports/recursive/Import_Recursive5.kerml.xt
- org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/imports/recursive/Import_Recursive6.kerml.xt
- org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/imports/recursive/Import_Recursive7.kerml.xt
- org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/imports/recursive/KerMLImportRecursiveTest.java
- org.omg.kerml.xtext/src/org/omg/kerml/xtext/scoping/KerMLScope.xtend
- org.omg.kerml.xtext/src/org/omg/kerml/xtext/validation/KerMLValidator.xtend
- org.omg.sysml.xpect.tests/src/org/omg/sysml/xpect/tests/validation/valid/KernelLibraryTest.sysml.xt
This pull request includes an update to the implementation of ST6RI-311 to remove the restriction of recursive import to only packages.
> ST6RI-311 (Updated) Name resolution with recursive package import

- org.omg.sysml.jupyter.jupyterlab/src/main/mode.ts
Please see description and analysis in Jira issue [ST6RI-350](https://openmbee.atlassian.net/browse/ST6RI-350).
> ST6RI-350 Web page freezes in JupyterLab when an unmatched single quote is typed

- org.omg.sysml.interactive/src/org/omg/sysml/interactive/SysMLInteractive.java
- org.omg.sysml.interactive/src/org/omg/sysml/interactive/VizResult.java
- org.omg.sysml.jupyter.kernel/src/main/java/org/omg/sysml/jupyter/kernel/magic/Viz.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/SysML2PlantUMLSvc.java
It's a corner-cutting solution but better than nothing ;)
> ST6RI-341: Help option for the %viz command (PlantUML)

- org.omg.sysml.jupyter.kernel/build.gradle
> ST6RI-370 Include license in Jupyter kernel archive

- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/SysML2PlantUMLText.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VActionMembers.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VCompartment.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VComposite.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VDefault.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VPath.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VStructure.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VTraverser.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VTree.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/Visitor.java
Visualize connectors with dot-notation expressions.
This PR includes a bug fix of interconnection view.
> ST6RI-411: Dot-notation expression visualization (PlantUML)

- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/SysML2PlantUMLStyle.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VDefault.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VMetadata.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VPath.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/Visitor.java
This update visualizes metadata with note shape notations.  The connector rendering is using the current PlantUML one and it does not render connectors with dotted lines and it may not render the terminal dot.  For these, I would need to update PlantUML later.
> ST6RI-424: Visualize metadata (PlantUML)

- org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/testsuite/MemberNameTests_FeatureSubset.kerml.xt
- org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/testsuite/MemberNameTests_MultipleInheritance2_Rdef.kerml.xt
- org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/testsuite/ShadowingTests_CircleProblem4_Rdef.kerml.xt
- org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/testsuite/ShadowingTests_ImportAndInnerClassesNamesAreTheSameGoodCase1_2_Rdef.kerml.xt
- org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/testsuite/ShadowingTests_ImportAndInnerClassesNamesAreTheSameGoodCase1_Rdef.kerml.xt
- org.omg.kerml.xtext/src/org/omg/kerml/xtext/scoping/KerMLScopeProvider.xtend
- org.omg.sysml.xpect.tests/src/org/omg/sysml/xpect/tests/simpletests/FeaturePathTest.sysml.xt
- sysml/src/examples/Simple Tests/FeaturePathTest.sysml
See [ST6RI-443](https://openmbee.atlassian.net/browse/ST6RI-443) for analysis and description of resolution.
> ST6RI-443 Feature chain can resolve incorrectly in a connector end

- org.omg.sysml.plantuml/META-INF/MANIFEST.MF
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/PRelation.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/SysML2PlantUMLStyle.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/SysML2PlantUMLText.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VActionMembers.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VSequence.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VTraverser.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/Visitor.java
- sysml/src/validation/17-Sequence Modeling/17b-Sequence-Modeling.sysml
> ST6RI-436: Visualize sequence diagrams (PlantUML)

- org.omg.kerml.xtext/.launch/Save KerML2JSON.launch
- org.omg.kerml.xtext/META-INF/MANIFEST.MF
- org.omg.kerml.xtext/src/org/omg/kerml/xtext/util/KerML2JSON.java
- org.omg.kerml.xtext/src/org/omg/kerml/xtext/util/KerML2XMI.java
- org.omg.kerml.xtext/src/org/omg/kerml/xtext/util/KerMLRepositorySaveUtil.java
- org.omg.sysml.interactive.tests/src/org/omg/sysml/interactive/tests/GlobalNameRedefinitionTest.java
- org.omg.sysml.interactive/.launch/SysML Interactive.launch
- org.omg.sysml.interactive/META-INF/MANIFEST.MF
- org.omg.sysml.interactive/src/org/omg/sysml/interactive/SysMLInteractive.java
- org.omg.sysml.interactive/src/org/omg/sysml/interactive/SysMLInteractiveHelp.java
- org.omg.sysml.interactive/src/org/omg/sysml/interactive/VizResult.java
- org.omg.sysml.jupyter.kernel/src/main/java/org/omg/sysml/jupyter/kernel/SysMLKernel.java
- org.omg.sysml.jupyter.kernel/src/main/java/org/omg/sysml/jupyter/kernel/magic/Export.java
- org.omg.sysml.jupyter.kernel/src/main/java/org/omg/sysml/jupyter/kernel/magic/Show.java
- org.omg.sysml.jupyter.kernel/src/main/java/org/omg/sysml/jupyter/kernel/magic/Viz.java
- org.omg.sysml.xtext/.launch/Save SysML2JSON with Derived.launch
- org.omg.sysml.xtext/.launch/Save SysML2JSON with Implicit.launch
- org.omg.sysml.xtext/.launch/Save SysML2JSON.launch
- org.omg.sysml.xtext/src/org/omg/sysml/xtext/util/SysML2JSON.java
- org.omg.sysml/src/org/omg/sysml/util/ElementUtil.java
- org.omg.sysml/src/org/omg/sysml/util/SysMLUtil.java
- org.omg.sysml/src/org/omg/sysml/util/traversal/facade/impl/ApiCommitProcessingFacade.java
- org.omg.sysml/src/org/omg/sysml/util/traversal/facade/impl/ApiElementProcessingFacade.java
- org.omg.sysml/src/org/omg/sysml/util/traversal/facade/impl/JsonElementProcessingFacade.java
- org.omg.sysml/src/org/omg/sysml/util/traversal/facade/impl/JsonExportProcessingFacade.java
refactor: decouple JSON exporting from API committing
> ST6RI-390 Create a utility for serializing a model to a file using a JSON representation

- org.omg.sysml.jupyter.installer/assembly.xml
- org.omg.sysml.jupyter.installer/install.bat
- org.omg.sysml.jupyter.installer/install.py
- org.omg.sysml.jupyter.installer/install.sh
- org.omg.sysml.jupyter.jupyterlab/package.json
instead of embedding in installer archive
> ST6RI-372 Update Jupyter installer to pull from conda-forge and npm

- org.omg.sysml.jupyter.installer/README.adoc
- org.omg.sysml.jupyter.installer/assembly.xml
- org.omg.sysml.jupyter.installer/install.bat
- org.omg.sysml.jupyter.installer/install.sh
- org.omg.sysml.jupyter.installer/pom.xml
Fix install script inclusion for package lifecycle
Update installer README to specify Java 11
> ST6RI-448 Strip qualifier from version included in Jupyter installer

- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VActionMembers.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VCompartment.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VDefault.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VPath.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VTree.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/Visitor.java
Show connections in compartments.  Flow connections are properly rendered with `sourceOutput` and `targetInput`.
> ST6RI-480: Show connections in compartments and render flow connections (PlantUML)

- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VCompartment.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VRequirement.java
Render RequirementConstraintMemberships in compartments when COMPMOST is enabled or the constraint is anonymous
> ST6RI-486: Render RequirementConstraintMemberships in compartments

- org.omg.sysml.xpect.tests/library.domain/Quantities and Units/SI.sysml
- org.omg.sysml.xpect.tests/library.domain/Quantities and Units/Time.sysml
- org.omg.sysml.xpect.tests/library.domain/Quantities and Units/USCustomaryUnits.sysml
- org.omg.sysml.xpect.tests/library.domain/Quantities and Units/UnitsAndScales.sysml
- sysml.library/Domain Libraries/Quantities and Units/SI.sysml
- sysml.library/Domain Libraries/Quantities and Units/Time.sysml
- sysml.library/Domain Libraries/Quantities and Units/USCustomaryUnits.sysml
- sysml.library/Domain Libraries/Quantities and Units/UnitsAndScales.sysml
- sysml/src/validation/15-Properties-Values-Expressions/15_13-Discretely Sampled Function Value.sysml
- sysml/src/validation/15-Properties-Values-Expressions/15_19-Materials with Properties.sysml
- sysml/src/validation/15-Properties-Values-Expressions/15_19a-Materials with Properties.sysml
This is the result of the first attempt to add a complete set of US Customary Unit definitions to the Quantity and Units Library.
It is still not fully complete, but it should provide a good temporary version.
A small number of problematic definitions in `USCustomaryUnits.sysml` are commented out.
A full update will be finalized in the coming 2022-01 sprint, issue [ST6RI-491](https://openmbee.atlassian.net/browse/ST6RI-491) together with issue [ST6RI-415](https://openmbee.atlassian.net/browse/ST6RI-415).
> ST6RI-416 Complete SI and USCustomaryUnits libraries

- org.omg.sysml/syntax-gen/org/omg/sysml/lang/sysml/impl/DefinitionImpl.java
Fixes bug identified in Issue #334 .
> ST6RI-517 DefinitionImpl::getOwnedConnection should return all ConnectorAsUsages

- org.omg.sysml.jupyter.jupyterlab/yarn.lock
Merging this PR will result in a dependabot re-scan that should auto-close these other PRs:
* https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/pull/336
* https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/pull/344
> ST6RI-530 update yarn.lock to address security alerts

- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/SysML2PlantUMLStyle.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VActionMembers.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VComposite.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VDefault.java
Visualize feature values as bindings.
> ST6RI-571: Visualization of feature values as bindings (PlantUML)

- org.omg.sysml.plantuml/META-INF/MANIFEST.MF
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/SysML2PlantUMLStyle.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/SysML2PlantUMLText.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VCompartment.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VSequence.java
Update PlantUML by setting the dependent version to `1.2022.7.himi1`
> ST6RI-613: Update PlantUML to 1.2022.7.himi1

- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/CompartmentEntry.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/PRelation.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/SysML2PlantUMLStyle.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VActionMembers.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VBehavior.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VCase.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VCaseMembers.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VCompartment.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VDefault.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VPath.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VSSRMembers.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VTraverser.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VTree.java
This PR deals with the issue  reported in https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/issues/424
It shows start, done actions in actions, and entry and exit actions in states.
> ST6RI-619: properly show start, done, entry, exit actions (PlantUML)

- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VCompartment.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VDefault.java
- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VStructure.java
This PR shows short names in compartments.
> ST6RI-631: Show short names in compartments, hide empty subjects

- org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VBehavior.java
The trigger name of `Sig` below is wrongly rendered as `SigOccurrence`.  This PR fixes it by rendering the first parameter (`Sig`) only.
```
attribute def Sig;
state s1 {
state s11;
accept Sig then done;
}
```
> ST6RI-867 Trigger is not shown properly (PlantUML)
