org.omg.kerml.xtext.ide/pom.xml
org.omg.kerml.xtext.ui/pom.xml
org.omg.kerml.xtext/pom.xml
org.omg.kerml.xtext/src/org/omg/kerml/xtext/scoping/KerMLGlobalScope.xtend
org.omg.kerml.xtext/src/org/omg/kerml/xtext/scoping/KerMLScopeProvider.xtend
org.omg.sysml.xtext.ide/pom.xml
org.omg.sysml.xtext.ui/pom.xml
org.omg.sysml.xtext/pom.xml
org.omg.sysml/pom.xml
pom.xml

This change adds required configuration to the maven build to generate
Java files to the xtend-gen folders. This required adding extra pom.xml
files to the projects, as it is not possible for the previously used
tycho-pomless to add this project-specific configuration otherwise.

ST6RI-308 Adds Xtend compiler to the maven build configuration

---

org.omg.sysml.plantuml/META-INF/MANIFEST.MF
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/SysML2PlantUMLStyle.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/SysML2PlantUMLSvc.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/SysML2PlantUMLText.java

To ensure to use the fixed version of PlantUML, set the dependent version to the latest one.
I also fixed the default style is not properly chosen in Jupyter environment when we specify --style comptree with 
9d60bf2

ST6RI-321: Spurious "(T,blue)" shown in header of various def elements (PlantUML)

---

org.omg.kerml.expressions.xtext.ide/META-INF/MANIFEST.MF
org.omg.kerml.expressions.xtext.ui/META-INF/MANIFEST.MF
org.omg.kerml.expressions.xtext/META-INF/MANIFEST.MF
org.omg.kerml.owl.ide/META-INF/MANIFEST.MF
org.omg.kerml.owl.ui/META-INF/MANIFEST.MF
org.omg.kerml.owl/META-INF/MANIFEST.MF
org.omg.kerml.xpect.tests/META-INF/MANIFEST.MF
org.omg.kerml.xtext.ide/META-INF/MANIFEST.MF
org.omg.kerml.xtext.ui/META-INF/MANIFEST.MF
org.omg.kerml.xtext/META-INF/MANIFEST.MF
org.omg.sysml.feature/feature.xml
org.omg.sysml.interactive.tests/META-INF/MANIFEST.MF
org.omg.sysml.interactive/META-INF/MANIFEST.MF
org.omg.sysml.jupyter.jupyterlab/package.json
org.omg.sysml.plantuml.eclipse/META-INF/MANIFEST.MF
org.omg.sysml.plantuml.feature/feature.xml
org.omg.sysml.plantuml/META-INF/MANIFEST.MF
org.omg.sysml.xpect.tests/META-INF/MANIFEST.MF
org.omg.sysml.xtext.ide/META-INF/MANIFEST.MF
org.omg.sysml.xtext.ui/META-INF/MANIFEST.MF
org.omg.sysml.xtext/META-INF/MANIFEST.MF
org.omg.sysml/META-INF/MANIFEST.MF
pom.xml

Use propertyregex task in ant-contrib instead of using Javascript.

ST6RI-345: In OpenJDK11, maven build failed due to the lack of javascript support

---

org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VTraverser.java

Check circular relationships when traversing model elements.

ST6RI-355: Circular memberships cause stack overflow when visualized (PlantUML)

---

pom.xml

TravisCI failing to build tags ([ex](https://travis-ci.com/github/Systems-Modeling/SysML-v2-Pilot-Implementation/builds/220213353)), but not regular commits.
Upon local reproduction with verbose logging, the source of the issue was the following exception:
```
[ERROR] Internal error: org.eclipse.tycho.core.osgitools.OsgiManifestParserException: Exception parsing OSGi MANIFEST /home/i/SysML-v2-Pilot-Implementation/org.omg.sysml/META-INF/MANIFEST.MF: Invalid manifest header Bundle-Version: "${bundle-version}" : invalid version "${bundle-version}": non-numeric "${bundle-version}": For input string: "${bundle-version}" -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: org.eclipse.tycho.core.osgitools.OsgiManifestParserException: Exception parsing OSGi MANIFEST …
```

ST6RI-296 Fix continuous integration builds for tags

---

org.omg.sysml.jupyter.jupyterlab/src/main/mode.ts
org.omg.sysml.jupyter.kernel/src/main/resources/kernel/kernel.js
tool-support/syntax-highlighting/README.md
tool-support/syntax-highlighting/jupyter/kernel.js
tool-support/syntax-highlighting/jupyter/kernel_template.js
tool-support/syntax-highlighting/jupyter/mode.ts
tool-support/syntax-highlighting/jupyter/mode_template.ts
tool-support/syntax-highlighting/xtext_grammar_converter.py

In the end we decided to make this semi-automated: the generator script `xtext_grammar_converter.py` can be run on demand, after changes to the `xtext` grammars have been made, to automatically prepare for an intermediate or complete release.
The script is not included as part of CI, because that would potentially cause mutual dependencies as the generator replaces source code in the `jupyterLab` and `jupyter.kernel` modules.

ST6RI-365 Add syntax highlighting generation to automated build

---

org.omg.kerml.xtext/src/org/omg/kerml/xtext/util/KerML2XMI.java
org.omg.sysml.xtext/.launch/Save SysML2XMI without Libraries.launch
org.omg.sysml.xtext/src/org/omg/sysml/xtext/util/SysML2XMI.java
org.omg.sysml/src/org/omg/sysml/adapter/ElementAdapterFactory.java
org.omg.sysml/src/org/omg/sysml/adapter/MembershipAdapter.java

This PR updates the `KerML2XMI` and `SysML2XMI` utilities to generate XMI that uses the UUID `identifier` of an Element as its XMI ID. These IDs are then used for cross-references, rather than the default Xpaths.
It also includes a fix for the bug reported in [ST6RI-402 Member names are sometimes not written to XMI](https://openmbee.atlassian.net/browse/ST6RI-402).

ST6RI-389 Update XMI export to use UUIDs for XMI IDs

---

kerml/src/examples/Simple Tests/Expressions.kerml
org.omg.sysml/src/org/omg/sysml/util/ExpressionUtil.java
sysml.library/Kernel Library/ControlFunctions.kerml
sysml.library/Kernel Library/ControlPerformances.kerml
sysml.library/Kernel Library/FeatureAccessPerformances.kerml
sysml.library/Kernel Library/Occurrences.kerml
sysml.library/Kernel Library/Performances.kerml

This pull request updates the Kernel Library for the 2021-05 baseline.
1. A new association `SelfSameLifeLink` has been added to the Occurrences package.
2. A new `FeatureAccessPerformances` package has been added, with the following behaviors in it:
- `FeatureReferencingPerformance`
- `FeatureAccessingPerformance`
- `FeatureReadEvaluation`
- `FeatureWritePerformance`
3. The following new behaviors have been added to the `ControlPerformances` package:
- `IfPerformance`
- `IfThenPerformance`
- `IfElsePerformance`
- `IfThenElsePeformance`
- `LoopPerformance`
**Note:** There has been no update to the abstract syntax to make it convenient to use these new behaviors. That will done during the implementation of [ST6RI-387](https://openmbee.atlassian.net/browse/ST6RI-387), which has been …

ST6RI-386 Kernel libraries for feature access and control performances

---

org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/expression/PathExpressions.kerml.xt
org.omg.kerml.xtext/src/org/omg/kerml/xtext/scoping/KerMLScopeProvider.xtend
sysml/src/validation/14-Language Extensions/14c-Language Extensions.sysml

Updated `KerMLScopeProvider.featureRefNamespace` to return the `referent` of FeatureReferenceExpression as the relative namespace, rather than the `result`. The `result` should nominally subset the `referent`, giving it implicitly the same typing. But that implicit subsetting is only set when the `result` is transformed, which my not have happened yet during name resolution.

ST6RI-410 Name resolution can fail for PathStepExpression

---

sysml.library/Domain Libraries/Quantities and Units/ISQElectromagnetism.sysml
sysml.library/Domain Libraries/Quantities and Units/SI.sysml

Henry [H] defined as [Wb/A] should be an InductanceUnit as well as a PermeanceUnit, because Faraday's induction law imposes that electric current is induced by magnetic current.  So [H] should be defined as:
```
attribute H: PermeanceUnit, InductanceUnit = Wb/A { :>> longName = "henry"; }
```

ST6RI-414 Henry [H] should be an InductanceUnit as well as a PermeanceUnit

---

org.omg.sysml.jupyter.jupyterlab/yarn.lock

The following dependencies were explicitly targeted for upgrade, while the remainder are updated transitive dependencies:
* codemirror
* url-parse
* sanitize-html

ST6RI-420 Update JupyterLab dependencies

---

kerml/src/examples/Simple Tests/Features.kerml
org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/testsuite/ShadowingTests_CircleProblem4_FT.kerml.xt
org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/testsuite/ShadowingTests_ImportAndInnerClassesNamesAreTheSameBadCase1_Rdef.kerml.xt
org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/testsuite/ShadowingTests_ImportAndInnerClassesNamesAreTheSameBadCase2_Rdef.kerml.xt
org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/testsuite/ShadowingTests_SameNamesImportAsFeature_Rdef.kerml.xt
org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/testsuite/ShadowingTests_SameNamesImport_Rdef.kerml.xt
org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/testsuite/ShadowingTests_SameNamesInnerClassAndOuterClassWithAlias_FT.kerml.xt
org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/testsuite/ShadowingTests_SameNamesInnerClassAndOuterClass_FT.kerml.xt
org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/testsuite/ShadowingTests_SameNamesInnerClassAndOuterClass_Rdef.kerml.xt
org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/testsuite/SimpleImportTests_ImportPackageAndInheritanceFromContainer_FT.kerml.xt
org.omg.sysml.xpect.tests/src/org/omg/sysml/xpect/tests/validation/invalid/OccurrenceUsage_invalid.sysml.xt
org.omg.sysml.xpect.tests/src/org/omg/sysml/xpect/tests/validation/valid/PartUsage.sysml.xt
org.omg.sysml/src/org/omg/sysml/adapter/TypeAdapter.java

This PR updates the algorithm for adding a default general type so that it is added even if the type being declared already has an owned specialization of the same kind, unless the specialization is of a type that is already a subtype of the default type. See issue [ST6RI-398](https://openmbee.atlassian.net/browse/ST6RI-398) for the description of why this is necessary.
Actually, `TypeAdapter.addDefaultType` has been revised to add the default type unconditionally. But `TypeAdapter.doTransform` has also been revised to remove any unnecessary implicit general types, that is, any implicit types for which there is an owned specialization with a general type that conforms to the implicit type. This approach ensures that default types are always added as necessary for the purposes of …

ST6RI-398 Implicit specializations may be needed even if there are explicit ones

---

org.omg.kerml.xpect.tests/library/Objects.kerml
org.omg.sysml.xpect.tests/library.kernel/Objects.kerml
sysml.library/Kernel Library/Objects.kerml

Formerly, dot notation of the form `f_1.f_2. ... .f_n`, for _n > 1_, mapped to a hierarchy of (left associative) PathStepExpressions, one for each dot. This notation could be used in two ways:
1. As an evaluable Expression in its own right, either directly as an owned Expression or as a sub-Expression of some other Expression. In this case, `f_1` can be any Expression for which `f_2` is a Feature accessible from the result. All the other `f_i` must be Feature names.
2. To specify an end feature of a Connector (including ItemFlows). In this case, all the `f_i` must be feature names.
This PR replaces the use of PathStepExpressions in the second case with the new FeatureChaining construct available in the 2021-06 baseline. No change is being made at this time to the use of …

ST6RI-406 Dot notation for feature chains

---

org.omg.sysml.interactive/src/org/omg/sysml/interactive/SysMLInteractiveHelp.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VActionMembers.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VBehavior.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VComposite.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VDefault.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VMetadata.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VSequence.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VStateMachine.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VStateMembers.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VStructure.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VTree.java
org.omg.sysml/syntax-gen/org/omg/sysml/lang/sysml/impl/SatisfyRequirementUsageImpl.java

This PR fixes the visualization problems of:
- Unnamed actions and states are not rendered;
- Wrong `<<satisfy>>` links may appear when SatisfyRequirementUsage is incomplete;
- PlantUML error in sequence view reported in ST6RI-436.

ST6RI-437: Render unnamed actions and states, and remove inappropriate satisfying feature links. (PlantUML)

---

org.omg.sysml.xpect.tests/src/org/omg/sysml/xpect/tests/simpletests/UseCaseTest.sysml.xt
org.omg.sysml/syntax-gen/org/omg/sysml/lang/sysml/impl/IncludeUseCaseUsageImpl.java
sysml.library/Kernel Library/Occurrences.kerml
sysml/src/examples/Simple Tests/UseCaseTest.sysml

Note: The commit related to ST6RI-461 should have been pushed separately, but now that it is accidentally included in this PR, it is not worth the trouble to change it. The second commit contains the resolution to ST6RI-467.

ST6RI-467 Include Use Case names could not be resolved

---

README.adoc
org.omg.kerml.xtext/src-gen/org/omg/kerml/xtext/serializer/KerMLSemanticSequencer.java
org.omg.sysml.installer/SysML2.setup
org.omg.sysml.xpect.tests/pom.xml
org.omg.sysml.xtext/src-gen/org/omg/sysml/xtext/serializer/SysMLSemanticSequencer.java
pom.xml

Updated for Eclipse 2021-09:
1. `org.omg.sysml.installer/SysML2.setup`
2. Top level `pom.xml`
3. Top level `README.adoc`
Verified a clean install using the Oomph SysML2 install (for Mac x86_64). (Also requires a regeneration of all Xtext grammars and a rebuild of the workspace.)

ST6RI-470 Update to Eclipse version 2021-09

---

org.omg.sysml.xpect.tests/src/org/omg/sysml/xpect/tests/simpletests/VariabilityTest.sysml.xt
org.omg.sysml.xpect.tests/src/org/omg/sysml/xpect/tests/validation/valid/Variability.sysml.xt
org.omg.sysml.xtext/src/org/omg/sysml/xtext/validation/SysMLValidator.xtend
sysml/src/examples/Simple Tests/VariabilityTest.sysml

Updated the validation check for variants to ignore objective memberships.

ST6RI-468 Variation cases cause an error of "A variation must only have variant owned members."

---

org.omg.kerml.xtext/src/org/omg/kerml/xtext/scoping/KerMLScopeProvider.xtend
org.omg.sysml.xpect.tests/src/org/omg/sysml/xpect/tests/simpletests/EnumerationTest.sysml.xt
org.omg.sysml/src/org/omg/sysml/adapter/FeatureAdapter.java
org.omg.sysml/src/org/omg/sysml/util/ConnectorUtil.java
org.omg.sysml/src/org/omg/sysml/util/NamespaceUtil.java
sysml/src/examples/Metadata Examples/VerificationMetadataExample.sysml
sysml/src/examples/Simple Tests/EnumerationTest.sysml
sysml/src/examples/Vehicle Example/VehicleModel_1_Simplified_06_20_21.sysml
sysml/src/validation/10-Analysis and Trades/10b-Trade-off Among Alternative Configurations.sysml
sysml/src/validation/14-Language Extensions/14a-Language Extensions.sysml
sysml/src/validation/14-Language Extensions/14c-Language Extensions.sysml

This pull request includes the following changes:
1. Names in the value Expression of a FeatureValue resolve in the scope of the parent of the Feature with the FeatureValue, rather than in the scope of the Feature itself (resolves the bug as originally reported for ST6RI-476).
2. The initial Feature name in a FeatureChain used to specify a Connector related Feature is resolved in the scope of the parent of the Connector, rather than in the scope of the Connector itself.
3. If a Feature with a FeatureValue has no explicit owned Specializations, then an implicit Subsetting is added to the result of the value Expression of the FeatureValue.

ST6RI-476 Feature values resolve in scope of feature namespace

---

org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VMetadata.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/Visitor.java

Feature chains in metadata had been wrongly shown with "null".  By this fix, we can show RiskMetadataExample.

ST6RI-483: Show feature chains in metadata

---

org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/expression/PathExpressions.kerml.xt
org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/validation/PathTests_invalid.kerml.xt
org.omg.kerml.xtext/src/org/omg/kerml/xtext/util/KerML2XMI.java
org.omg.sysml.uml.ecore.importer/src/org/omg/sysml/uml/ecore/importer/CustomUML2EcoreConverter.java
org.omg.sysml/model/SysML.ecore
org.omg.sysml/model/SysML.uml
org.omg.sysml/syntax-gen/org/omg/sysml/lang/sysml/OperatorExpression.java
org.omg.sysml/syntax-gen/org/omg/sysml/lang/sysml/impl/OperatorExpressionImpl.java
org.omg.sysml/syntax-gen/org/omg/sysml/lang/sysml/impl/SysMLPackageImpl.java

This PR makes the following changes to fix the subject bug:
1. Updated `OperatorExpression::operand` in `SysML.uml` so it is derived and has no redefined properties. (A corresponding update has been made in the MagicDraw abstract syntax model so it will be included in future exports of `SysML.uml`.)
2. Revised the custom Ecore generation so that a composite property that is derived and has no subsetted or redefined properties remains a containment feature in the generated Ecore model.
As a result of above, `operand` is still a containment feature, as required by Xtext, but it is also marked as transient, so that it is not serialized in the XMI.
In addition, the `eContents()` method has been overridden in `OperatorExpressionImpl` to exclude `operand` from the contents traversal. As a …

ST6RI-489 OperatorExpression operands are serialized twice in XMI

---

sysml.library/Domain Libraries/Quantities and Units/SI.sysml

Applied manual corrections (from ST6RI-414) in SI.sysml for Henry and newton metre
When waking up I realized I had overlooked the manual correction from bug fix [ST6RI-414](https://openmbee.atlassian.net/browse/ST6RI-414). This problem will be fully resolved via issue [ST6RI-415](https://openmbee.atlassian.net/browse/ST6RI-415).

ST6RI-416 Complete SI and USCustomaryUnits libraries - Update: Applied manual corrections (from ST6RI-414) in SI.sysml

---

org.omg.sysml.jupyter.jupyterlab/package.json
org.omg.sysml.jupyter.jupyterlab/yarn.lock

fix: update nodejs dependencies
fix: lock ts to <4.4.0 to work around transient incompatibility, ref: https://github.com/jupyterlab/jupyterlab/issues/11520#issuecomment-1017216979
This should address existing dependabot alerts, for a little while at least (nature of the Javascript ecosystem). I have re-tested the JupyterLab extension after applying these changes and it looks good to me.

Update JupyterLab extension dependencies

---

sysml.library/Domain Libraries/Quantities and Units/ISQ.sysml
sysml.library/Domain Libraries/Quantities and Units/ISQBase.sysml
sysml.library/Domain Libraries/Quantities and Units/NIST_SP811_CGS.sysml
sysml.library/Domain Libraries/Quantities and Units/NIST_SP811_Imp.sysml
sysml.library/Domain Libraries/Quantities and Units/NIST_SP811_SI_deprecated.sysml
sysml.library/Domain Libraries/Quantities and Units/NIST_SP811_SI_recognized.sysml
sysml.library/Domain Libraries/Quantities and Units/Quantities.sysml
sysml.library/Domain Libraries/Quantities and Units/QuantityCalculations.sysml
sysml.library/Domain Libraries/Quantities and Units/SI.sysml
sysml.library/Domain Libraries/Quantities and Units/USCustomaryUnits.sysml
sysml.library/Domain Libraries/Quantities and Units/UnitsAndScales.sysml
sysml.library/Domain Libraries/Quantities and Units/VectorCalculations.sysml
sysml/src/examples/Analysis Examples/Vehicle Analysis Demo.sysml
sysml/src/examples/Individuals Examples/AnalysisIndividualExample.sysml
sysml/src/examples/Simple Tests/AliasTest.sysml
sysml/src/validation/10-Analysis and Trades/10c-Fuel Economy Analysis.sysml

The upgrade for generating the Q&U library packages from NIST SP811 is now reasonably complete. The generator splits the units defined in SP811 as follows:
- USCustomaryUnits.sysml (humanId `<USCU>`) only containing US Customary Units, This is the main package to be used by end-users.
- NIST_SP811_CGS (humanId `<CGS>`) 'Centimetre-Gram-Second System of Units' library
- NIST_SP811_Imp  (humanId `<Imp>`) 'Imperial (Canadian and UK) Units' library
- NIST_SP811_SI_recognized (humanId `<SI_recognized>`) 'International System of Units - Units recognized in SI' library
- NIST_SP811_SI_deprecated (humanId `<SI_deprecated>`) 'International System of Units - Deprecated units' library.
The last four provide complete coverage of all units and conversion factors defined in SP811, but are of limited …

ST6RI-491 Complete SI and USCustomaryUnits libraries (continued)

---

sysml.library/Kernel Library/Occurrences.kerml

Adds the following line to the definition of the association `Occurrences::PortionsOf`:
`binding portionOccurrence.portionOfLife[1] = portionedOccurrence.portionOfLife[1];`
This PR also resolves ST6RI-516 (Reverse order of PortionOf participant features), by reversing the order of the end features of `PortionOf`, `TimeSliceOf` and `SnapshotOf`.

ST6RI-504 Portions should have the same life as their portionsOf 

---

sysml.library/Domain Libraries/Quantities and Units/UnitsAndScales.sysml
sysml.library/Kernel Library/Collections.kerml

Fixed as discussed in [ST4MD-386](https://openmbee.atlassian.net/browse/ST4MD-386) and updated documentation, i.e.:
- Revised multiplicity of Array::dimensions: `feature dimensions: Positive[0..*] ordered nonunique;`
- Revised derivation of Array::flattenedSize: `feature flattenedSize : Positive[1] = dimensions->reduce '*' ?? 1;`
- Revised multiplicity of VectorMeasurementReference::dimensions: `attribute :>> dimensions : Positive[0..1];`
- Removed binding of `order `in ScalarMeasurementReference
- Redefined `attribute dimensions = ()` in ScalarMeasurementReference

ST6RI-513 Order constraint of VectorQuantityValue incorrect

---

kerml/src/examples/Simple Tests/Associations.kerml
org.omg.kerml.xpect.tests/library/Clocks.kerml
org.omg.kerml.xpect.tests/library/CollectionFunctions.kerml
org.omg.kerml.xpect.tests/library/Collections.kerml
org.omg.kerml.xpect.tests/library/Objects.kerml
org.omg.kerml.xpect.tests/library/Occurrences.kerml
org.omg.kerml.xpect.tests/library/Performances.kerml
org.omg.kerml.xpect.tests/library/SequenceFunctions.kerml
org.omg.kerml.xpect.tests/library/Triggers.kerml
org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/validation/AssociationTest_EndRedefinitionGoodCase.kerml.xt
org.omg.kerml.xtext/src/org/omg/kerml/xtext/validation/KerMLValidator.xtend
org.omg.sysml.xpect.tests/library.systems/Ports.sysml
org.omg.sysml/src/org/omg/sysml/util/ImplicitGeneralizationMap.java
sysml.library/Kernel Library/CollectionFunctions.kerml
sysml.library/Kernel Library/Objects.kerml
sysml.library/Kernel Library/Occurrences.kerml
sysml.library/Kernel Library/Performances.kerml
sysml.library/Kernel Library/SequenceFunctions.kerml
sysml.library/Systems Library/Ports.sysml
sysml/src/examples/Interaction Sequencing Examples/ServerSequenceModel.sysml

(For @conradbock)
This pull request updates the `Occurrence` and `Object` Kernel Library models for spatial and topology semantics.
_Occurrences_
- Add modeling for spatial aspects of `Occurrences` and for constructive relations on Occurrences of union, intersection and difference.
- Add associations to represent spatial relationships `SpaceSliceOf`, `SpaceShotOf` and `OutsideOf`, and the spacetime relationship `WithOut`.
_Objects_
- Add specializations of `Object` for `Body`, `Surface`, `Curve` and `Point`, of inner space dimension 3, 2, 1 and 0, respectively.
- Add `StructuredSpaceObject` to represent an `Object` that is broken up into cells of the same or lower inner space dimension (faces, edges and vertices).
The pull request also fixes the following related bugs:
- ST6RI-518 The …

ST6RI-505 Spatial & topology Kernel Library model for occurrences

---

org.omg.sysml.jupyter.kernel/src/main/java/org/omg/sysml/jupyter/kernel/ISysML.java
org.omg.sysml.jupyter.kernel/src/main/java/org/omg/sysml/jupyter/kernel/SysMLKernel.java
org.omg.sysml/src/org/omg/sysml/util/SysMLUtil.java

This PR intends to fix the bug that the SysML kernel may wrongly load model library files in UTF-8 encoding.
We have two approaches to fix this bug: one is that explicitly specifying UTF-8 encoding to load SysML files by using something like `XtextResource.setEncoding`; the other is that system's default file encodings with System property.
However, the first approach  would require to modify more codes related to Xtext so that the fix and test should be more complicated.  So I decided to take the second approach in this PR because we confirmed this problem did not occur under the environment where the default encoding is UTF-8.
In this fix, I propose to extract SysML kernel initialization part to the separate method `initialize()` because the most part of `main()` comes from IJava …

ST6RI-531: Non-ASCII characters may not be parsed properly in Jupyter

---

sysml.library/Domain Libraries/Geometry/ShapeItems.sysml
sysml.library/Kernel Library/Objects.kerml
sysml.library/Kernel Library/Occurrences.kerml
sysml/src/examples/Geometry Examples/CarWithShapeAndCSG.sysml

**Occurrences.kerml**
- `spaceShotOf` multiplicity: [1..] to [0..*].  Some occurrences aren't snapshots.
- invariants:
-- `innerSpaceDimension`: removed redundancy with feature type.
-- `spaceBoundaryOf`: isClosed to !isClosed
-- `spaceBoundary`: moved to after spaceBoundaryOf.
-- `SpaceShotOf`: Added that innerSpaceDimenion must be strictly lower (compare to SpaceSliceOf), not sure how it got left out.
- `spaceBoundary` description: reworded to avoid "of which".
- Typo in multiple places ("occcurrence" -> "occurrence").
**Objects.kerml**
`genus`: changed type Integer to Natural, simplified invariant.
**ShapeItems.sysml**
- Added `PlanarCurve`, to match PlanarSurface and used it below.
- Added multiplicities to quantification attributes (length, etc).
- `PlanarSurface::shape` typed by …

ST6RI-532 Minor fixes to space modeling & shape library

---

org.omg.sysml/src/org/omg/sysml/lang/sysml/util/SysMLLibraryUtil.xtend

In Jupyter environment, SysML kernel indirectly calls setModelLibraryDirectory with the kernel directory string, which contains OS-specific path syntax such as backslash and drive letter and volume separator (`c:`).  This makes inconsistencies in isModelLibrary path matching.
In this fix, setModelLibrary normalize the directory string to EMF URI form and use drivePath() if it's not null; otherwise use path().  Also I changed the name of `modelLibraryDirectory` to `modelLibraryPath` because it's normalized to URI path syntax.
isModelLibray() also checks if path() is not null because some EMF Resource URI does not have path() part.
This fix also adds getModelLibraryPath() getter method for other modules to obtain the library path.

ST6RI-539: SysMLLibraryUtil.isModelLibrary does not work in Jupyter on Windows

---

sysml.library/Domain Libraries/Geometry/ShapeItems.sysml
sysml.library/Kernel Library/Objects.kerml
sysml.library/Kernel Library/Occurrences.kerml

**ShapeItems.sysml**
- Added topo structure and constraints to Path.
- Added more LengthValue attributes with unrestricted domains when they were needed across unrelated item defs (semiMajorAxis, semiMinorAxis, xoffset, yoffset, baseLength,baseWidth).
- Replaced alot of WithinBoth connectors with bindings, as they should've been before (also in Objects::StructuredSpaceObject).
- Added shapes below (indentation for subclassing).  HP and I decided not to support truncation as in STEP because they can be specified by CSG (except the prism, which could be considered a truncated cuboid) and change the topology, violating the typical subclassing expectations (eg, a truncated cone is not a cone).  Added supporting shapes, like triangles, and generalizations, like polyhedra and toroids (some …

ST6RI-527 Shape library additions

---

sysml.library/Domain Libraries/Geometry/ShapeItems.sysml
sysml.library/Kernel Library/Occurrences.kerml
sysml.library/Systems Library/Items.sysml
sysml/src/examples/Geometry Examples/CarWithEnvelopingShape.sysml

These are the remaining space modeling capabilities (except bounding box orientation, taking as a separate issue for later).  Slides at [ST4MD-392](https://openmbee.atlassian.net/browse/ST4MD-392?focusedCommentId=13514) (May 16, 2022).
**Occurrences.kerml**
Added inner and outer occurrence references nested under Occurrence::spaceBoundary.  These are space slices that also have no spaceBoundary, where the outer one surrounds the inner ones (see SurroundedBy below).  Also added inverse constraint to spaceBoundaryOf.
Added associations from Occurrence to itself (indirectly) specializing OutsideOf:
- JustOutsideOf linking occurrences that have space slices with no space between them (MatesWith).
- MatesWith specializing JustOutsideOf linking occurrences that have no space between them.
- …

ST6RI-540 Space modeling additions

---

org.omg.sysml/syntax-gen/org/omg/sysml/lang/sysml/impl/TypeImpl.java

Changed `TypeImpl::addInheritedMemberships` to use `TypeUtil::getGeneralTypesOf`.

ST6RI-546 Inherited membership computation does not handle feature chains properly

---

org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/visibility/VisibilityTests_PublicImportAsFeatureAlias_Rdef.kerml.xt
org.omg.sysml/src/org/omg/sysml/adapter/UsageAdapter.java
org.omg.sysml/syntax-gen/org/omg/sysml/lang/sysml/impl/FeatureImpl.java
org.omg.sysml/syntax-gen/org/omg/sysml/lang/sysml/impl/TypeImpl.java
sysml/src/examples/Vehicle Example/SysML v2 Spec Annex B VehicleModel.sysml
sysml/src/examples/Vehicle Example/VehicleModel_1_Simplified.sysml
sysml/src/training/33. Verification/Verification Case Usage Example.sysml
sysml/src/training/37. Allocation/Allocation Definition Example.sysml
sysml/src/training/37. Allocation/Allocation Usage Example.sysml
sysml/src/validation/06-Individual and Snapshots/6-Individual and Snapshots.sysml
sysml/src/validation/08-Requirements/8-Requirements.sysml
sysml/src/validation/09-Verification/9-Verification-simplified.sysml
sysml/src/validation/12-Dependency Relationships/12b-Allocation-1.sysml
sysml/src/validation/12-Dependency Relationships/12b-Allocation.sysml

Fixed the transformation for variation typing in `UsageAdapter`.
This also allow the implementation of `FeatureImpl::isFeaturedWithin` so that features are not considered "within" package-level features. This results in a better validation for the featuring types of the target of subsetting relationships.

ST6RI-552 Variants of a variation usage are not getting proper implicit subsettings

---

org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VActionMembers.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VCompartment.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VSSRMembers.java
sysml/src/examples/State Space Representation Examples/CartSample.sysml
sysml/src/examples/State Space Representation Examples/EVSample.sysml

Actions of SSR have `input`, `output`, and `stateSpace` but they were not rendered properly.  `input` and `output` are features having FeatureDirectionKind so that the visualizer could render these features but it did not render their vector components.  `stateSpace` does not have FeatureDirectionKind and it was not rendered at all.
I also added two SSR examples, CartSample and EVSample, in `sysml/src/examples/State Space Representation Examples` directory.

ST6RI-547: Render members of State Space Representation (SSR) in Action

---

org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VActionMembers.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VCompartment.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VDefault.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VPath.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VSSRMembers.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VTree.java
sysml/src/examples/State Space Representation Examples/CartSample.sysml
sysml/src/examples/State Space Representation Examples/EVSample.sysml

When we subset or redefine features with feature chains, they were not shown because VPath did not care about such feature chains.  This fix renders such relationships.

ST6RI-551 Specializations to feature chains are not rendered (PlantUML)

---

sysml.library/Domain Libraries/Requirement Derivation/DerivationConnections.sysml
sysml.library/Domain Libraries/Requirement Derivation/RequirementDerivation.sysml
sysml/src/examples/Requirements Examples/RequirementDerivationExample.sysml

This pull request adds a Requirement Derivation Domain Library model and metadata to address the following SysML v2 RFP requirement:
> RQT 1.3.4: Requirement Derivation
>
> Proposals for SysML v2 shall include a capability to represent a derive relationship that relates a derived requirement to a source requirement.
The new library includes two packages.
**`DerivationsConnections` Package**
1. `Derivation` is an abstract connection definition with no ends, but having two non-end requirement usages, one for an `originalRequirement` and one for all corresponding `derivedRequirements`. This connection definition also asserts that the `originalRequirement` value is not one of the `derivedRequirements` values and, if the check of the `originalRequirement` is true, then the checks for all the …

ST6RI-560 Derived requirement relationship

---

sysml.library/Domain Libraries/Metadata/ModelingMetadata.sysml

This pull request adds a `Refinement` metadata definition to the existing `ModelingMetadata` library model in the Metadata Domain Library, in order to address the following SysML v2 RFP requirement:
> CRC 1.3.07: Refine Relationship
>
>Proposals for SysML v2 shall include a capability to represent a Refine Relationship where the refined side of the relationships refers to the more precisely specified element.
The `Refinement` metadata (short name `refinement`) can be applied to a dependency declaration to model a refinement relationship in which the source elements refine the target elements. No formal semantics is provided for this relationship at this time. For example:
```
part def DesignModel;
package Specification;
requirement def SystemRequirements;
#refinement dependency …
```

ST6RI-559 Refinement relationship

---

sysml.library/Domain Libraries/Cause and Effect/CausationConnections.sysml
sysml.library/Domain Libraries/Cause and Effect/CauseAndEffect.sysml
sysml/src/examples/Cause and Effect Examples/CauseAndEffectExample.sysml

This pull request adds a Cause and Effect Domain Library model and metadata to address the following SysML v2 RFP requirement:
> CRC 1.3.04: Cause-Effect Relationship
>
> Proposals for SysML v2 shall include a capability to represent a Cause-Effect Relationship where one side of the relationship refers to the cause and the other side of the relationship refers to the effect.
The new library includes two packages.
**`CausationConnections` Package**
1. `Multicausation` is an abstract connection definition with no ends, but having two non-end features that collect cause occurrences and effect occurrences. This connection definition also asserts constraints that the the intersection of causes and effects is empty and that all causes exist (i.e, have at least started) before all effects.
2. …

ST6RI-558 Cause-effect relationship

---

sysml.library/Domain Libraries/Metadata/ParametersOfInterestMetadata.sysml

This pull request adds a Metadata Domain Library model to address the following SysML v2 RFP requirement:
>ANL 1.03: Parameters of Interest
>
>Proposals for SysML v2 shall include the capability to identify the key parameters of interest including measures-of-effectiveness (MoE) and other key measures of performance (MoP).

ST6RI-556 Metadata for parameters of interest

---

sysml.library/Domain Libraries/Metadata/ImageMetadata.sysml

This PR introduces the `ImageMetadata` library model, as part of the SysML Metadata Domain Library. This library model includes the following.
1. `Image` attribute definition, which captures the data necessary for the physical definition of a graphical image. This can be used directly within `Icon` annotations (see below), or it can be used to create library models of image usages that can be referenced from `Icon` annotations. Alternatively, the images themselves can be physically stored in separate resources from the SysML model and referenced by URI. 
2. `Icon` metadata definition, which can be used to annotate a model element with an image to be used to show render the element on a diagram and/or a small image to be used as an adornment on a graphical or textual rendering. …

ST6RI-561 Metadata for element icon images

---

sysml.library/Kernel Library/StatePerformances.kerml
sysml.library/Kernel Library/TransitionPerformances.kerml

This pull request fixes errors and redundancies in StatePerformances.kerml and TransitionPerformances.kerml found when reviewing them for further enhnacements.
- Updates successions and constraints to account for HappensBefore being fully asymmetric now.  This includes adding StatePerformance::`nonDoMiddle` derived as middle minus do (these are the modeler-defined steps).
- Replaces invariants on features nested under the features (which would be satisfied by features having no values) with dynamic multiplicities on the features.
- Removes `isTriggerDuring` invariant in StatePerformance that was redundant with the one in TransitionPeformance. StatePerformance:`:isTriggerDuring` defaults to true to constrain all the corresponding TransitionPeformances to that, modelers can set it to false …

ST6RI-568/569 Fix StatePerformance::acceptFirst, triggerDuring invariants; StateTransitionPerformance AcceptFirst -> TriggerDuring

---

kerml/src/examples/Simple Tests/Classes.kerml
org.omg.sysml.xpect.tests/library.systems/Items.sysml
org.omg.sysml.xpect.tests/src/org/omg/sysml/xpect/tests/simpletests/OccurrenceTest.sysml.xt
org.omg.sysml.xpect.tests/src/org/omg/sysml/xpect/tests/simpletests/PartTest.sysml.xt
org.omg.sysml/src/org/omg/sysml/adapter/ActionUsageAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/ConstraintUsageAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/FeatureAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/ItemUsageAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/OccurrenceUsageAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/UsageAdapter.java
org.omg.sysml/src/org/omg/sysml/util/ImplicitGeneralizationMap.java
sysml.library/Domain Libraries/Geometry/SpatialItems.sysml
sysml.library/Domain Libraries/Quantities and Units/Time.sysml
sysml.library/Kernel Library/Clocks.kerml
sysml.library/Kernel Library/Objects.kerml
sysml.library/Kernel Library/Occurrences.kerml
sysml.library/Kernel Library/Performances.kerml
sysml.library/Kernel Library/SpatialFrames.kerml
sysml.library/Kernel Library/Triggers.kerml
sysml.library/Systems Library/Items.sysml
sysml/src/examples/Simple Tests/OccurrenceTest.sysml
sysml/src/examples/Simple Tests/PartTest.sysml

This PR updates the model library to allow each occurrence to have a "local clock", which is used as the default clock for triggers within an occurrence. This update allows, for example, the following:
```
part context {
// This defines a local clock used by default within the “context” part.
part :>> localClock = Time::Clock();
state behavior {
entry; then S1;
state S1;
transition
first S1
// The time instant in the trigger is, by default, 
// relative to context::localClock.
accept at Iso8601DateTime("22-05-12T00:00:00")
then S2;
state S2;
}
}
```
**Kernel Model Library**
1. _Clocks._ 
- Rename `defaultClock` to `universalClock`.
- Change the default for the `clock` parameter of `TimeOf` and `DurationOf` from `defaultClock` to `localClock`.
2. _Occurrences._
- Add a `localClock` feature …

ST6RI-573 Added localClock to Occurrence, used as trigger clock default.

---

org.omg.kerml.expressions.xtext.ide/META-INF/MANIFEST.MF
org.omg.kerml.expressions.xtext.ui/META-INF/MANIFEST.MF
org.omg.kerml.expressions.xtext/META-INF/MANIFEST.MF
org.omg.kerml.owl.ide/META-INF/MANIFEST.MF
org.omg.kerml.owl.ui/META-INF/MANIFEST.MF
org.omg.kerml.owl/META-INF/MANIFEST.MF
org.omg.kerml.xpect.tests/META-INF/MANIFEST.MF
org.omg.kerml.xtext.ide/META-INF/MANIFEST.MF
org.omg.kerml.xtext.ui/META-INF/MANIFEST.MF
org.omg.kerml.xtext/META-INF/MANIFEST.MF
org.omg.sysml.feature/feature.xml
org.omg.sysml.interactive.tests/META-INF/MANIFEST.MF
org.omg.sysml.interactive/META-INF/MANIFEST.MF
org.omg.sysml.jupyter.jupyterlab/package.json
org.omg.sysml.jupyter.kernel/gradle.properties
org.omg.sysml.plantuml.eclipse/META-INF/MANIFEST.MF
org.omg.sysml.plantuml.feature/feature.xml
org.omg.sysml.plantuml/META-INF/MANIFEST.MF
org.omg.sysml.xpect.tests/META-INF/MANIFEST.MF
org.omg.sysml.xtext.ide/META-INF/MANIFEST.MF
org.omg.sysml.xtext.ui/META-INF/MANIFEST.MF
org.omg.sysml.xtext/.launch/Save SysML2XMI.launch
org.omg.sysml.xtext/META-INF/MANIFEST.MF
org.omg.sysml/META-INF/MANIFEST.MF
org.omg.sysml/src/org/omg/sysml/delegate/ItemFlow_itemType_SettingDelegate.java
pom.xml

This pull request removes a spurious line from the `ItemFlow_itemType_SettingDelegate::basicGet` method that caused an `IndexOutOfBoundsException` during the derivation of the `itemType` property of an `ItemFlow`/`FlowConnectionUsage` with no item feature.

ST6RI-578 SysML2XMI error from ItemFlow::itemType setting delegate

---

org.omg.sysml/src/org/omg/sysml/util/ConnectorUtil.java
sysml/src/examples/Simple Tests/ActionTest.sysml

This pull request corrects the computation of the featuring type of an implicit connector/connection. This was causing the reported bug that, when the first end of a conditional succession (in the SysML textual notation) was an inherited feature, then a warning was reported on the second end.

ST6RI-586 First end of a conditional succession being an inherited feature causes a warning

---

org.omg.sysml/syntax-gen/org/omg/sysml/lang/sysml/impl/UsageImpl.java

In the update for ST6RI-500, the default for the `isComposite` property of a `Usage` was inadvertently changed from `true` to `false`. This pull request restores the correct default.

ST6RI-588 Usage::isComposite defaults to false instead of true

---

org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/Visitor.java

To render type names, it used getName() but it may be null if the types are inherits without their own name.  Use getEffectiveName() instead.

ST6RI-589: Show conjugate port types (PlantUML)

---

org.omg.sysml/src/org/omg/sysml/delegate/ItemFlow_itemType_SettingDelegate.java
sysml.library/Systems Library/Connections.sysml

Updates `ItemFlow_itemType_SettingDelegate` to check whether the `itemFeature` of an `ItemFlow` is null before getting the types of that feature.

ST6RI-595 ItemFlow.getItemType can throw a null pointer exception

---

org.omg.kerml.xtext/src/org/omg/kerml/xtext/util/KerML2JSON.java
org.omg.kerml.xtext/src/org/omg/kerml/xtext/util/KerML2XMI.java
org.omg.kerml.xtext/src/org/omg/kerml/xtext/util/KerMLRepositorySaveUtil.java
org.omg.kerml.xtext/src/org/omg/kerml/xtext/util/KerMLTraversalUtil.java
org.omg.sysml.interactive/src/org/omg/sysml/interactive/SysMLInteractive.java
org.omg.sysml/src/org/omg/sysml/util/SysMLUtil.java

Immediately after opening a Jupyter notebook, doing a `%show DerivationConnections` command results in an error because `DerivationConnections` cannot be resolved. This is because `DerivationConnections.syml` is the last library model loaded, so the resolution search starts with that resource in memory. However, the global scope provider is used for name resolution, and the starting resource for resolution is considered to be a local scope, not part of the global scope. As a result `DerivationConnections` is not resolved.
This pull request fixes the error by creating a dummy resource if the resolution of a magic command argument is attempted immediately after loading the libraries. The last library model is then no longer the last resource in the resource set, and, therefore is properly …

ST6RI-594 Cannot resolve names in the lastly loaded resource in Jupyter

---

org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/SysML2PlantUMLText.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VCompartment.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VDefault.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VPath.java

This PR fixes the problem that does not render FlowConnectionUsages.   This is partly caused by the metamodel change and the visualizer was confused them as ActionUsage.  So we capture them with caseConnectionUsage() in VCompartment and VDefault.

ST6RI-596:  Fixed to show flow connection usages

---

org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/PRelation.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VAction.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VActionMembers.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VCase.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VComposite.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VDefault.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VStateMachine.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VStructure.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/Visitor.java

In SHOWINHERITED style, inherited elements can be multiple and we cannot identify sources only with a element.  So I used node id to identify a source.

ST6RI-601: Specialization relationships are not rendered properly with SHOWINHERITED style (PlantUML)

---

org.omg.sysml/src/org/omg/sysml/delegate/ItemFlow_itemFlowFeature_SettingDelegate.java

Fixes the computation of `ItemFlow::itemFlowFeature` in `ItemFlow_itemFlowFeature_SettingDelegate`, which fixes the computation of `sourceOutputFeature` and `targetInputFeature`.

ST6RI-607 ItemFlow::getSourceOutputFeature and getTargetInputFeature are broken

---

org.omg.sysml.execution/src/org/omg/sysml/execution/expressions/ExpressionEvaluator.java
org.omg.sysml.interactive.tests/src/org/omg/sysml/interactive/tests/ExpressionEvaluationTest.java
org.omg.sysml/src/org/omg/sysml/expressions/util/EvaluationUtil.java

This PR fixes a bug in user-defined function evaluation as implemented in ST6RI-599 (PR #405). In particular, the problem will occur if a function recursively calls itself with a binding for a parameter that depends on the previous value of that parameter (for example `Fact(x - 1)` in the recursive definition of a factorial function). In this case, a reference to the parameter results in evaluation of the argument expression, which causes an infinite regress of access to the parameter.
This is a result of the evaluation algorithm (as previously implemented) not really fully instantiating invocations. The argument expressions of an invocation should be evaluated in the context of the caller of the invocation, and the evaluated result then being bound to the parameter for the invocation. …

ST6RI-608 Recursion can cause problems with expression evaluation

---

sysml.library/Systems Library/StandardViewDefinitions.sysml

Added initial version of `StandardViewDefinitions.sysml` library package, as designed in the SST Graphical Specification WG, and introduced in release 2022-08 of the SysML Specification, clause 9.2.18.1 Views Overview.
Note: The corresponding code snippet in SysML Specification, clause 9.2.18.1, has been updated as well, so it is identical.

ST6RI-598 Library models for standard views

---

org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/CompartmentEntry.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VCompartment.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VDefault.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VRequirement.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VStructure.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/Visitor.java

Documentations in RequirementUsages were redundantly rendered in the form of comments as well as in compartments because they are a kind of comments so that the visualizer render them as comments as well.  By this fix, the visualizer render documents in compartments and if it's the case, it does not render them as comments.

ST6RI-587: Documentation is redundantly rendered as comments (PlantUML)

---

org.omg.sysml/src/org/omg/sysml/util/traversal/facade/impl/JsonElementProcessingFacade.java

The reported bug happened when an import relationship to a package appeared in a model before the declaration of that package. The graph traversal utility traverses the model graph by following the owned relationships of elements, so, in this case, the package referenced in the import had not yet been processed when the import relationship was processed, and neither had the owning elements of the package. Unfortunately, for historical reasons, the traversal algorithm was only considering elements to have identifiers after they had been processed, which means no IDs were yet available to set the `owner` (and other `owning...`) properties of the package, causing the bug.
This pull request updates  `JsonElementProcessingFacade::getIdentified` so that it uses the `elementId` of an Element, …

ST6RI-604 Textual package ordering breaks derivation of owner properties

---

org.omg.sysml.xpect.tests/library.systems/Connections.sysml
sysml.library/Systems Library/Connections.sysml

This pull requests add missings specializations by `Connections::MessageConnection` of `Actions::Action` and by `Connections::messageConnections` of `Actions::actions`.

ST6RI-614 Connections::MessageConnection should specialize Actions::Action

---

org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/CompartmentEntry.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/SysML2PlantUMLStyle.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VCase.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VCaseMembers.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VCompartment.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VDefault.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VPath.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VSSRMembers.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VTraverser.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VTree.java

Previously, the visualizer could show subjects with typeOf relationship only such as
```
subject s : Part;
```
However, it could not render bindings nor substrings such as:
```
subject sub = part;
subject sub :> part;
```
So we decided to render subjects with distinct nodes to show these relationships.

ST6RI-618: Show subjects as distinct nodes (PlantUML)

---

org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/CompartmentEntry.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/PRelation.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/SysML2PlantUMLStyle.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VActionMembers.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VBehavior.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VCase.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VCaseMembers.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VCompartment.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VDefault.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VPath.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VSSRMembers.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VTraverser.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VTree.java

The visualizer rendered half-circle edge to show variant memberships, but the standard notation uses circle-plus.  This PR is for aligning the notation.

ST6RI-621: Align variant visualization to the standard notation

---

sysml.library/Domain Libraries/Requirement Derivation/RequirementDerivation.sysml

This PR corrects the `baseTypes` for `OriginalRequirementMetadata`  to `originalRequirements` and `DerivedRequirementMetadata` to `derivedRequirements`. These had been switched.

ST6RI-617 Base types switched in RequirementDerivation

---

org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VComposite.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VDefault.java

The current visualizer does not render bindings between ports in interconnection view.   So far we tested parameters but had not tested ports.

ST6RI-627: Render bindings between ports

---

sysml.library/Domain Libraries/Analysis/.meta
sysml.library/Domain Libraries/Analysis/.project
sysml.library/Domain Libraries/Analysis/StateSpaceRepresentation.sysml
sysml.library/Domain Libraries/Cause and Effect/.meta
sysml.library/Domain Libraries/Cause and Effect/.project
sysml.library/Domain Libraries/Cause and Effect/CausationConnections.sysml
sysml.library/Domain Libraries/Geometry/.meta
sysml.library/Domain Libraries/Geometry/.project
sysml.library/Domain Libraries/Metadata/.meta
sysml.library/Domain Libraries/Metadata/.project
sysml.library/Domain Libraries/Metadata/ImageMetadata.sysml
sysml.library/Domain Libraries/Metadata/ParametersOfInterestMetadata.sysml
sysml.library/Domain Libraries/Quantities and Units/.meta
sysml.library/Domain Libraries/Quantities and Units/.project
sysml.library/Domain Libraries/Requirement Derivation/.meta
sysml.library/Domain Libraries/Requirement Derivation/.project
sysml.library/Domain Libraries/Requirement Derivation/DerivationConnections.sysml
sysml.library/Domain Libraries/Requirement Derivation/RequirementDerivation.sysml
sysml.library/Kernel Libraries/Kernel Data Type Library/.meta
sysml.library/Kernel Libraries/Kernel Data Type Library/.project
sysml.library/Kernel Libraries/Kernel Function Library/.meta
sysml.library/Kernel Libraries/Kernel Function Library/.project
sysml.library/Kernel Libraries/Kernel Semantic Library/.meta
sysml.library/Kernel Libraries/Kernel Semantic Library/.project
sysml.library/Systems Library/.meta
sysml.library/Systems Library/.project

Added hand-created `.project` and `.meta` files to each model library directory under `sysml.library`, consistent with the 2022-11 baseline specification for project interchange. With these metadata files included, compressing each directory into an archive gives a legal project interchange (`.kpar`) file using the textual notation as the model interchange format (`.sysml`).
Creating project interchange files using JSON as the interchange format will be handled in a future task.

ST6RI-574 Organize model libraries into interchange projects

---

org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/InheritKey.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VPath.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VTree.java

Connections referring to redefined features could not be rendered correctly.  Rather, the visualizer connected to the original feature rather than the redefined feature.  This PR fixes this issue.

ST6RI-630: Connections referring to redefined features are not properly rendered (PlantUML)

---

org.omg.sysml.xpect.tests/library.systems/StandardViewDefinitions.sysml
sysml.library/Systems Library/StandardViewDefinitions.sysml

The set of view defs in `StandardViewDefinitions.sysml` was simplified following advice by the Graphical Specification WG to:
1. General View (gv) - replacing MemberView
2. Interconnection View (iv)
3. Action Flow View (afv)
4. State Transition View (stv)
5. Sequence View (sv)
6. Case View (cv) - generalizing and replacing UseCaseView, AnalysisCaseView, VerificationCaseView
7. Geometry View (gev)
8. Grid View (grv)
9. Browser View (bv) - replacing ContainmentView
The textual (doc) descriptions were merged and adapted where necessary, and aligned with the metamodel concepts from the reflection library packages `KerML.kerml` and `SysML.sysml`.

ST6RI-634 Update StandardViewDefinitions library package

---

sysml.library/Kernel Libraries/Kernel Semantic Library/Occurrences.kerml
sysml.library/Kernel Libraries/Kernel Semantic Library/Performances.kerml

This pull request addresses association cross-navigation ("end") features that currently can have values without corresponding links, where the semantics for them is currently given. It adds sufficiency to these associations, moving their necessary conditions to one of the cross navigation features.  It also adds logical relations between some features and associations (inverses, intersections, etc).
- Necessary conditions in associations other than on end features are moved to one of the cross navigation features, using `that `and `self `to identify (what would be) link participants.  Cross navigation features are added when there weren't any to move the specifications to (`withoutOccurrences`, `timeCoincidentOccurrences`, `outsideOfOccurrences`,
and `surroundedByOccurrences`). This is …

ST6RI-633 Add inverses and move necessary association conditions to cross-nav features in Kernel Semantic Library

---

org.omg.sysml/syntax-gen/org/omg/sysml/lang/sysml/impl/LiteralBooleanImpl.java

In the Kernel abstract syntax, no default value is given for `LiteralBoolean::value`. Normally, if no default is specified in the Ecore metamodel for a Boolean property, the EMF generation will give the field in the Java `Impl` class the default value `false`. However, the constant `VALUE_EDEFAULT` the `LiteralBooleanImpl`was marked as `@generated NOT` and given a value of `true`. This had been done to support the initial implementation of `Invariant` and `AssertConstraintUsage` elements, for reasons that no longer apply. So, this pull request returns `LiteralBooleanImpl.VALUE_EDEFAULT` to its generated value of `false`.

ST6RI-632 LiteralBooleanImpl.VALUE_EDEFAULT is set to "true"

---

org.omg.sysml/src/org/omg/sysml/adapter/TransitionUsageAdapter.java
org.omg.sysml/src/org/omg/sysml/util/ImplicitGeneralizationMap.java
sysml.library/Systems Library/Actions.sysml

The implicit specialization implemented for `TransitionUsages `used as "conditional successions" in action models has been `Action::transitions`. However, this is typed by `TransitionAction,` while conditional-succession `TransitionUsages` need to be typed by `DecisionTransitionAction`. This pull request adds the feature `Action::decisionTransitions`, subsetting `Actions::transition`, which is then used as the implicit specialization for conditional successions.
The pull request also fixes a bug in `TransitionUsageAdapter::getDefaultSupertype` for the case of a conditional succession in an `ActionDefinition`.

ST6RI-635 Conditional successions need to be typed by DecisionTransitionAction

---

org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VStructure.java

The current visualizer prints textual notation for feature values and if it does not have a separator such as leading spaces or equal sign, the results looks just concatenated with the feature name.  This PR inserts an equal or space before the feature values if the corresponding text has no leading spaces.

ST6RI-639 Incorrect rendering if no separator before a feature value (PlantUML)

---

org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/Visitor.java
org.omg.sysml/src/org/omg/sysml/delegate/Type_multiplicity_SettingDelegate.java
org.omg.sysml/src/org/omg/sysml/util/FeatureUtil.java
sysml.library/Kernel Libraries/Kernel Semantic Library/Base.kerml
sysml/src/examples/Simple Tests/PartTest.sysml

The `Type_multiplicity_SettingDelegate` implements the derivation of the `Type::multiplicity` property. The current implementation returns the first `ownedMember` of a `Type` that is a `Multiplicity`, if there is one, and, if there isn’t, returns the `multiplicity` of the first direct supertype of the `Type` (if any). However, a `Type` (particularly a `Feature`) can have multiple supertypes with `multiplicities`, and it is not clear what rule should be used to pick one. Picking the first one, as currently done, is not really justified unless all the supertype `multiplicites` are required to be the same, which is too tight a restriction. On the other hand, picking, say, the `multiplicity` with the narrowest range would require that the bounds of the `multiplicities` be model-level …

ST6RI-636 Update multiplicity derivation

---

sysml.library/Kernel Libraries/Kernel Semantic Library/Occurrences.kerml

This pull request makes some additional fixes to the Kernel Semantic Library model `Occurrences`, found when updating the specification documentation after PR #442.

ST6RI-633-1 Add inverses and move necessary association conditions to cross-nav features in Kernel Semantic Library - Update

---

org.omg.sysml.editor.feature/.project
org.omg.sysml.editor.feature/.settings/org.eclipse.core.resources.prefs
org.omg.sysml.editor.feature/build.properties
org.omg.sysml.editor.feature/feature.xml
org.omg.sysml.feature/feature.xml
org.omg.sysml.site/category.xml
pom.xml

This PR adds the new `org.omg.sysml.edit` and `org.omg.sysml.editor` plugins to the Maven build and to `org.omg.sysml.feature`, so they are included in the `org.omg.sysml.site` for Eclipse installation. (This was accidentally not included in PR #449 for the 2022-12 release.
**Note.** This update is intentionally consistent with 2022-12, and does not include the planned URI and abstract sytnax updates from ST6RI-622 and ST6RI-643 for 2023-01.

ST6RI-644 Add the new editor projects to the Eclipse installation

---

sysml.library/Kernel Libraries/Kernel Semantic Library/StatePerformances.kerml

Adds StatePerformance::incomingTransitionTrigger, constrained in StateTransitionPerformance to be a MessageTransfer accepted to trigger into the transition target (if it's a StatePerformance).

ST6RI-641 Access to triggering event from target state

---

sysml.library/Kernel Libraries/Kernel Semantic Library/ControlPerformances.kerml

Constrains earlier/laterOccurrence of Decision/MergePerformance::outgoing/incomingHBLink to be the performance.

ST6RI-649 Decision/MergePerformance outgoing/incomingHBLink should come from/go to the performance

---

sysml.library/Kernel Libraries/Kernel Semantic Library/Links.kerml
sysml.library/Kernel Libraries/Kernel Semantic Library/Transfers.kerml

Adds readonly to
- Link::`participant`
- BinaryLink::`source`/`target`
- Otherwise the values could be flipped and potentially not affect `participant` (couldn't find where the libs formally require these values to appear in `participant` in the order declared)
- Removed `nonunique`, since these features always have exactly one value.
- Transfer::`isInstant`, FlowTransfer::`iMove`/`isPush`
These indicate what a transfer as a whole (life) will be doing, shouldn't change during it.

ST6RI-329 Transfer::isMove,isPush,isInstant and Link::participants should be constant/read-only

---

org.omg.sysml.execution/src/org/omg/sysml/execution/expressions/ExpressionEvaluator.java
org.omg.sysml.interactive.tests/src/org/omg/sysml/interactive/tests/ExpressionEvaluationTest.java
org.omg.sysml.interactive.tests/src/org/omg/sysml/interactive/tests/ModelLevelEvaluationTest.java
org.omg.sysml/src/org/omg/sysml/expressions/functions/PowerFunction.java

This PR adds `^` as an allowable alternative name for the exponentiation operator `**` during model-level expression evaluation. It also fixes a null-pointer exception that can occur during full expression evaluation when an invocation expression is ill-formed without any type.

ST6RI-650 '^' should be implemented as a exponential operator

---

org.omg.sysml/src/org/omg/sysml/util/ImplicitGeneralizationMap.java
sysml/src/examples/Simple Tests/ActionTest.sysml

The the `ImplicitGeneralizationMap` included the following entry for `ActionUsageImpl`:
`put(ActionUsageImpl.class, "enclosedPerformance", "Performances::performance::enclosedPerformance");`
The qualified name in this entry contains two errors: the `p` in `performance` should be upper case, and `enclosedPerfromance` should have a final `s`. As a result, the name was not resolving and, e.g., a referential `ActionUsage` nested in and `ActionDefinition` or `ActionUsage` was not getting the required implicit specialization to `Performances::Performance::enclosedPerformance`.
This PR corrects the above errors.

ST6RI-652 Implicit specialization broken for ActionUsage as enclosedPerformance

---

org.omg.sysml.xpect.tests/library.systems/States.sysml
org.omg.sysml/src/org/omg/sysml/adapter/ActionUsageAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/CalculationUsageAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/StateUsageAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/UsageAdapter.java
org.omg.sysml/src/org/omg/sysml/util/ImplicitGeneralizationMap.java
sysml.library/Systems Library/States.sysml
sysml/src/examples/Simple Tests/StateTest.sysml

1. Revises the implicit specialization in `ActionUsageAdapter` so that composite entry and exit actions do _not_ subset `Action::subactions`, since `StateAction` redefines `subaction` to exclude entry and exit actions.
2. Updates `ActionUsageAdapter` to use the `ImplicitGeneralizationMap` to get the target of computed redefinitions of `ActionUsages` owned via `StateSubactionMembership` or `TransitionFeatureMembership` (rather than using hardcoded constants in the adapter).
3. Removes the subsetting by `StateAction::doAction` of `subaction`, because `subaction` is composite and `doAction` is not.

ST6RI-653 Entry and exit actions incorrectly subset Action::subactions

---

org.omg.sysml.xpect.tests/library.systems/AnalysisCases.sysml
org.omg.sysml.xpect.tests/library.systems/Cases.sysml
org.omg.sysml.xpect.tests/library.systems/Requirements.sysml
org.omg.sysml.xpect.tests/library.systems/UseCases.sysml
org.omg.sysml.xpect.tests/library.systems/VerificationCases.sysml
org.omg.sysml/src/org/omg/sysml/adapter/AnalysisCaseUsageAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/CalculationUsageAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/CaseUsageAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/ConcernUsageAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/ConstraintUsageAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/RequirementUsageAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/StateUsageAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/UsageAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/UseCaseUsageAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/VerificationCaseUsageAdapter.java
org.omg.sysml/src/org/omg/sysml/util/ImplicitGeneralizationMap.java
org.omg.sysml/src/org/omg/sysml/util/UsageUtil.java
sysml.library/Systems Library/AnalysisCases.sysml
sysml.library/Systems Library/Cases.sysml
sysml.library/Systems Library/Requirements.sysml
sysml.library/Systems Library/UseCases.sysml
sysml.library/Systems Library/VerificationCases.sysml

1. Makes various features of `RequirementCheck` composite:
- `assumptions` and `constraints`, since **`assume`** and **`require`** declarations parse as composite (also makes them subsets of `Performance::subperformances`).
- `subrequirements`, since it subsets `constraints`.
- `concerns`, since it subsets `constraints` (actually, makes it instead a subset of `subrequirements`, since concerns are requirements).
2. Makes `Cases::subcases`, `AnalysisCases::subAnalysisCases`, `VerificationCases::subVerificationCases` and `UseCases::subUseCases` all composite, since they indirectly subset `Actions::subactions`, which is composite.
3. Updates implicit specialization implementation as necessary for the above, and also adds entries to the `ImplicitGeneralizationMap` to support subsetting for …

ST6RI-655 Assumed and required constraints should be composite

---

org.omg.kerml.xtext/src/org/omg/kerml/xtext/util/KerML2XMI.java
org.omg.sysml.xtext/src/org/omg/sysml/xtext/util/SysML2XMI.java
org.omg.sysml/src/org/omg/sysml/delegate/Element_qualifiedName_SettingDelegate.java
org.omg.sysml/src/org/omg/sysml/util/ElementUtil.java
org.omg.sysml/src/org/omg/sysml/util/UUIDDigest.java
org.omg.sysml/syntax-gen/org/omg/sysml/lang/sysml/impl/ElementImpl.java
org.omg.sysml/syntax-gen/org/omg/sysml/lang/sysml/impl/LibraryPackageImpl.java

This PR revises `ElementImpl::getElementId` and `LibraryPackage::getElementId` so that the UUIDs for standard library elements with a non-null `qualifiedName` are generated deterministically as name-based UUIDs. Each such UUID is constructed from a _name space identifier_ and a _name_ (as defined in the UUID specification), which are determined as follows:
- For the top-level standard library package:
- _name space identifier_ is the `NameSpace_URL` UUID given in the UUID specification (which is `6ba7b812-9dad-11d1-80b4-00c04fd430c8`).
- _name_ is the URL constructed by prepending `https://www.omg.org/KerML/` to the name of the package, converted to bytes using a `UTF-8` encoding.
- For any element directly or indirectly contained in the top-level standard library package (for which that …

ST6RI-640 Deterministic UUIDs for standard library elements

---

sysml.library/Kernel Libraries/Kernel Semantic Library/Occurrences.kerml

Subset Occurrence::`self `from `spaceTimeCoincidentOccurrences` (was added in PR #442 for [ST6RI-633](https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/pull/442)), because the existing subsets from `time`/`spaceSlices` don't imply coincidence.

ST6RI-657 Occurrence::self should subset spaceTimeCoincidentOccurrences

---

sysml.library/Kernel Libraries/Kernel Semantic Library/Occurrences.kerml

Corrections to "concident" related elements in Occurrences.kerml.
In Occurrence::
- `spaceTimeCoincidentOccurrences`:
- Changed subsets to `timeCoincidentOccurrences, spaceEnclosedOccurrences` (was `spaceTimeEnclosedOccurrences`, which subsets `timeEnclosedOccurrences, spaceEnclosedOccurrences`, but `timeCoincidentOccurrences` already subsets `timeEnclosedOccurrences`).
- Added InsideOf connector to make it circular (space-coincident, there is no spaceCoincidentOccurrences, can move the connector to that if FTF adds it).
- `spaceEnclosedOccurrences`, reversed `smaller/largerSpace` (`that` should be the `largerSpace`, it was treating it as the `smallerSpace`).
- `timeCoincidentOccurrences`, subset `this`/`thatOccurrence` from the inherited `shorter`/`longerOccurrence` and reversed the …

ST6RI-658 spaceTimeCoincidentOccurrences should subset timeCoincidentOccurrences

---

org.omg.sysml.xpect.tests/library.systems/AnalysisCases.sysml
org.omg.sysml.xpect.tests/library.systems/UseCases.sysml
org.omg.sysml.xpect.tests/library.systems/Views.sysml
sysml.library/Systems Library/AnalysisCases.sysml
sysml.library/Systems Library/UseCases.sysml
sysml.library/Systems Library/Views.sysml

Changed the subsetting of `UseCases::UseCase::includedUseCases` from `subUseCases` to `enclosedPerformances`. This was necessary because `includedUseCases` is referential (it is subsetted by `IncludeUseCaseUsages`, which are always referential) and `subUseCases` is composite.

ST6RI-662 UseCase::includedUseCases should not subset subUseCases

---

sysml.library/Systems Library/AnalysisCases.sysml
sysml.library/Systems Library/Cases.sysml

This PR includes two changes to models in the Systems Model Library:
1. `Cases` – The binding of the subject of the objective of a `Case` to `Case::result` is changed to a default. The binding in `Case` conflicted with the binding of the subject of the objective of a `VerificationCase` to the `VerificationCase` subject, rather than the result. A default, on the other hand, can be overridden.
2. `AnalysisCases` – The default for the subject of the objective is overridden in `AnalysisCase` to be a mandatory binding to `AnalysisCase::result`. This is consistent with the specification documentation for `AnalysisCase`.
The above updates were included in the models in the Systems Model Library as delivered for the fourth revised submission to OMG.

ST6RI-663 Case::obj should not bind its subject to Case::result

---

org.omg.sysml/src/org/omg/sysml/adapter/ElementAdapter.java
org.omg.sysml/src/org/omg/sysml/util/TypeUtil.java

After PR #440 (ST6RI-631), empty subjects of requirements and cases are no longer shown when visualized using PlantUML within Eclipse. This PR corrects a bug that caused empty subjects to sometimes still be shown when visualized in Juptyer Lab.
The cause of the bug was that the effective name of an "empty" subject of a requirement usage was not being returned correctly in the Jupyter environment. The underlying reason for this was due to the transformation that adds an implicit subject to the base requirement usage `requirementChecks` being run automatically when the `Requirements` library model is loaded into memory in the Eclipse environment, but not in the Jupyter environment. This PR updates the utility method for getting the subject of a requirement or case to ensure that this …

ST6RI-667 Empty subjects are not hidden in Jupyter visualization (PlantUML)

---

org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/SysML2PlantUMLStyle.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VAction.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VCompartment.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VStateMachine.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VStateMembers.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VStructure.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/Visitor.java

So far the visualizer did not distinguish `perform action` and `perform` or `exhibit state` and `exhibit`.  So it visualize actions and states with `<<perform action>>` and `<<exhibit state>>` for both cases.  This PR renders such `perform` and `exhibit` with `<<perform>>` or `<<exhibit>>`
This PR also fixes the following issues:
- `^` was not shown in compartments.
-  specializations are not shown in the action view.
-  `<<state>>` stereotype is not shown in the mixed view.

ST6RI-482: Render <<perform>> and <<exhibit>> for just `perform` and `exhibit` instead of <<perform action>> and <<exhibit state>>

---

sysml/src/examples/Geometry Examples/VehicleGeometryAndCoordinateFrames.sysml
sysml/src/validation/03-Function-based Behavior/3c-Function-based Behavior-structure mod-1.sysml
sysml/src/validation/15-Properties-Values-Expressions/15_01-Constants.sysml
sysml/src/validation/15-Properties-Values-Expressions/15_03-Value Expression.sysml
sysml/src/validation/15-Properties-Values-Expressions/15_06-System of Quantities.sysml
sysml/src/validation/15-Properties-Values-Expressions/15_07-System of Units and Scales.sysml
sysml/src/validation/15-Properties-Values-Expressions/15_08-Range Restriction.sysml
sysml/src/validation/15-Properties-Values-Expressions/15_10-Primitive Data Types.sysml
sysml/src/validation/15-Properties-Values-Expressions/15_11-Variable Length Collection Types.sysml
sysml/src/validation/15-Properties-Values-Expressions/15_19a-Materials with Properties.sysml

This PR resolves the following left-over TODOs in various SysML validation case and example files were resolved.
1. `3c-Function-based Behavior-structure mod-1`
- `TODO: Destroy the link object.`
<br/>Added action to destroy the connection using `OccurrenceFunctions::destroy`.
2. `15_03-Value Expression`
- `TODO: Change profileDepth by adding tolerance: profileDepth: LengthValue = @i{6.0 ± 0.5} [mm];`
<br/>Instead of specifying a tolerance the following constraint was added:    
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`constraint hasLegalProfileDepth {profileDepth >= 3.5 [mm]}`
and the `profileDepth` value was changed from binding to default:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`attribute profileDepth: LengthValue default 6.0 [mm];`
3. `15_06-System of Quantities`
- `TODO: Support definition …

ST6RI-669 Resolved outstanding TODOs in SysML validation cases and examples

---

org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/parsing/ParsingTests_Indexing.kerml.xt
org.omg.kerml.xtext/src/org/omg/kerml/xtext/validation/KerMLValidator.xtend
org.omg.sysml/src/org/omg/sysml/adapter/OperatorExpressionAdapter.java
sysml/src/examples/Geometry Examples/VehicleGeometryAndCoordinateFrames.sysml

Updates `OperatorExpressionAdapter::addIndexingResultSubsetting` to ensure that the `seq` argument is transformed before trying to use its result parameter as the target of the implicit subsetting of the result parameter of an index expression. This subsetting not being set correctly was the underlying cause of the bug being fixed.

ST6RI-676 Feature chain expression result typing can fail when used with indexing

---

org.omg.sysml.jupyter.jupyterlab/package.json
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VStructure.java

I thought it had been fixed but maybe due to some merge, this issue again appeared.  The fix is just correcting the regular expression pattern.

ST6RI-680 An unnecessary `=` is rendered when we use `:=` in feature values. 

---

org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VBehavior.java

The visualizer could not properly render feature chains in behavioural rendering, used by Action, State, Interconnection, Case views.  The example below
```
action a {
action a1 {
action a11;
}
action a12;
first a1.a11 then a12;
}
```
is wrongly rendered as:

ST6RI-697 Feature chains in Action or Interconnection views are not properly rendered

---

org.omg.sysml.interactive.tests/src/org/omg/sysml/interactive/tests/ModelLevelEvaluationTest.java
org.omg.sysml/src/org/omg/sysml/expressions/functions/ArithmeticFunction.java
org.omg.sysml/src/org/omg/sysml/expressions/functions/DivideFunction.java

This pull request fixes two bugs in the evaluation of model-level evaluable expressions:
1. _ST6RI-695 Integer division is implemented incorrectly._ The `org.omg.sysml.expressions.functions.DivideFunction` class implemented the division of two integers using truncating Java integer division. However, the KerML `IntegerFunctions::'/'` function returns a `Rational` number is intended to not be truncating.
2. _ST6RI-696 Unary Real operator evaluation is implemented incorrectly._ The `org.omg.sysml.expressions.functions.ArithmeticFunction::invoke` made the call `unaryRealOp((Integer)y)` to evaluate a unary `Real` operator. This should instead have been `unaryRealOp((Double)x)`.

ST6RI 695/696 Integer division and unary Real operator evaluation are implemented incorrectly

---

kerml/src/examples/Simple Tests/Circular.kerml
org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/parsing/ParsingTests_CircularReferences.kerml.xt
org.omg.sysml.xpect.tests/src/org/omg/sysml/xpect/tests/simpletests/PartTest.sysml.xt
org.omg.sysml/src/org/omg/sysml/adapter/TypeAdapter.java
org.omg.sysml/src/org/omg/sysml/util/TypeUtil.java
sysml/src/examples/Simple Tests/PartTest.sysml

Corrects the `TypeAdapter::removeUnnecessaryImplicitGeneralTypes` method so that it does not remove implicit specializations from types that are part of a chain of circular owned specializations. Declarations such as the following no longer produce errors:
```
part def A :> A;
part def B :> C;
part def C :> B;
```
In the case of a circle of two or more types, the implicit specialization is added to the lexically last one processed (e.g., `C` in the example above), though it would also have been legal to add the implicit specialization to any or all of the types in the circle.

ST6RI-698 Implicit specializations not added when there are circular owned specializations

---

org.omg.kerml.xtext/src/org/omg/kerml/xtext/validation/KerMLValidator.xtend
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VCompartment.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VComposite.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VDefault.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VPath.java
org.omg.sysml/src/org/omg/sysml/adapter/ConnectionUsageAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/ConnectorAdapter.java
org.omg.sysml/src/org/omg/sysml/delegate/AssignmentActionUsage_referent_SettingDelegate.java
org.omg.sysml/src/org/omg/sysml/delegate/Connector_connectorEnd_SettingDelegate.java
org.omg.sysml/src/org/omg/sysml/delegate/IfActionUsage_ifArgument_SettingDelegate.java
org.omg.sysml/src/org/omg/sysml/util/ConnectorUtil.java
org.omg.sysml/src/org/omg/sysml/util/TypeUtil.java

This pull request fixes bugs in the implementation of several derived property computations.
1. _ST6RI-690 Connector::connectorEnd implementation is incorrect._ The KerML specification defines the derivation for `Type::endFeature` to be all `features` of a `Type` that have `isEnd = true`. The property `Connector::connectorEnd` redefines `endFeature` and inherits the same derivation. This was implemented correctly in `Type_endFeature_SettingDelegate`, but `Connector_connectorEnd_SettingDelegate` had a separate derivation that only returned owned end features.
2. _ST6RI-692 AssignmentActionUsage_referent_SettingDelegate is incorrect._ The implementation in this setting delegate presumed that the `referent` of an `AssignmentActionUsage` would be the first non-parameter member of the action. …

ST6RI-690/692/693/694 Various derivation implementations are incorrect

---

org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/parsing/ParsingTests_BadScopeWithOnlyTwoSingleDot.kerml.xt
org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/parsing/ParsingTests_BadScopeWithOnlyTwoSingleDotAtTheEnd.kerml.xt
org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/validation/FeatureChain_invalid.kerml.xt
org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/validation/MembershipTests_Distinguishability.kerml.xt
org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/validation/MultiplicityRange_invalid.kerml.xt
org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/validation/ShortNameTests_Distinguishibility1.kerml.xt
org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/validation/ShortNameTests_Distinguishibility2.kerml.xt
org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/validation/Specialization_invalid.kerml.xt
org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/validation/TypeRelationships_invalid.kerml.xt
org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/validation/Type_Multiplicity_invalid.kerml.xt
org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/validation/Type_Relationships_invalid.kerml.xt
org.omg.kerml.xtext/src/org/omg/kerml/xtext/validation/KerMLValidator.xtend
org.omg.sysml.xpect.tests/src/org/omg/sysml/xpect/tests/simpletests/ConnectionTest.sysml.xt
org.omg.sysml.xpect.tests/src/org/omg/sysml/xpect/tests/validation/invalid/CalculationUsage_Invalid2.sysml.xt
org.omg.sysml.xpect.tests/src/org/omg/sysml/xpect/tests/validation/invalid/Relationship_invalid_relatedElement0.sysml.xt
org.omg.sysml.xtext/src/org/omg/sysml/xtext/validation/SysMLValidator.xtend
org.omg.sysml/src/org/omg/sysml/adapter/OperatorExpressionAdapter.java
org.omg.sysml/src/org/omg/sysml/lang/sysml/util/SysMLLibraryUtil.xtend
sysml.library/Domain Libraries/Cause and Effect/CausationConnections.sysml
sysml.library/Kernel Libraries/Kernel Semantic Library/Transfers.kerml
sysml/src/examples/Simple Tests/ConjugationTest.sysml

This pull request implements validation constraints that are in the [KerML 1.0 Beta 1](https://www.omg.org/spec/KerML/1.0/Beta1/PDF) abstract syntax, but which were not previously implemented in the pilot implementation. In addition, the `org.omg.kerml.xtext.KerMLValidator.xtend` class has been reorganized so that there is one check method per metclass, with each validation constraint for the metaclass checked within that method. Further, the normative constraint names are now used as the error codes for the corresponding validation checks.
The following newly implemented constraints could potentially result in errors being flagged in models where they had not been before.
1. `validateSpecializationSpecificNotConjugated`
2. `validateTypeAtMostOneConjugator`
3. …

ST6RI-685 Update KerML validation based on normative validation constraints

---

org.omg.sysml.xpect.tests/library.systems/AnalysisCases.sysml
org.omg.sysml.xpect.tests/library.systems/Cases.sysml
org.omg.sysml.xpect.tests/library.systems/Connections.sysml
org.omg.sysml.xpect.tests/library.systems/Views.sysml
org.omg.sysml.xpect.tests/src/org/omg/sysml/xpect/tests/simpletests/ConnectionTest.sysml.xt
org.omg.sysml.xpect.tests/src/org/omg/sysml/xpect/tests/validation/invalid/ActionUsage_invalid.sysml.xt
org.omg.sysml.xpect.tests/src/org/omg/sysml/xpect/tests/validation/invalid/CaseSubjectObjective_Invalid.sysml.xt
org.omg.sysml.xpect.tests/src/org/omg/sysml/xpect/tests/validation/invalid/CaseUsage_Invalid.sysml.xt
org.omg.sysml.xpect.tests/src/org/omg/sysml/xpect/tests/validation/invalid/IndividualUsage_Invalid.sysml.xt
org.omg.sysml.xpect.tests/src/org/omg/sysml/xpect/tests/validation/invalid/OccurrenceUsage_invalid.sysml.xt
org.omg.sysml.xpect.tests/src/org/omg/sysml/xpect/tests/validation/invalid/PartUsage_invalid.sysml.xt
org.omg.sysml.xpect.tests/src/org/omg/sysml/xpect/tests/validation/invalid/PortUsage_Invalid.sysml.xt
org.omg.sysml.xpect.tests/src/org/omg/sysml/xpect/tests/validation/invalid/RequirementSubject_Invalid.sysml.xt
org.omg.sysml.xpect.tests/src/org/omg/sysml/xpect/tests/validation/invalid/StateUsage_invalid.sysml.xt
org.omg.sysml.xpect.tests/src/org/omg/sysml/xpect/tests/validation/invalid/TransitionUsage_invalid.sysml.xt
org.omg.sysml.xpect.tests/src/org/omg/sysml/xpect/tests/validation/invalid/Variability_invalid.sysml.xt
org.omg.sysml.xtext/src/org/omg/sysml/xtext/validation/SysMLValidator.xtend
org.omg.sysml/src/org/omg/sysml/adapter/UsageAdapter.java
org.omg.sysml/syntax-gen/org/omg/sysml/lang/sysml/impl/LifeClassImpl.java
sysml.library/Systems Library/Connections.sysml
sysml/src/examples/Arrowhead Framework Example/AHFNorwayTopics.sysml
sysml/src/examples/Simple Tests/ConnectionTest.sysml
sysml/src/examples/Vehicle Example/SysML v2 Spec Annex A SimpleVehicleModel.sysml
sysml/src/validation/14-Language Extensions/14c-Language Extensions.sysml

This pull request implements validation constraints that are in the [SysML 2.0 Beta 1](https://www.omg.org/spec/SysML/2.0/Beta1/Language/PDF) abstract syntax, but which were not previously implemented in the pilot implementation. In addition, the `org.omg.sysml.xtext.SysMLValidator.xtend` class has been reorganized so that there is one check method per metclass, with each validation constraint for the metaclass checked within that method. Further, the normative constraint names are now used as the error codes for the corresponding validation checks.
The following newly implemented constraints could potentially result in errors being flagged in models where they had not been before.
1. `validateDefinitionVariationSpecialization`
2. `validateUsageVariationSpecialization`
3. …

ST6RI-686 Update SysML validation based on normative validation constraints

---

org.omg.sysml/src/org/omg/sysml/adapter/FlowConnectionUsageAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/SuccessionAsUsageAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/TransitionUsageAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/TypeAdapter.java
org.omg.sysml/src/org/omg/sysml/delegate/TransitionUsage_source_SettingDelegate.java
org.omg.sysml/src/org/omg/sysml/util/FeatureUtil.java
org.omg.sysml/src/org/omg/sysml/util/UsageUtil.java

This pull request includes the following changes:
1. Revises the computation of `TransitionUsage::source` to be consistent with the specification: "The <code>source</code> of a <code>TransitionUsage</code> is given by the <code>memberElement</code> of its first <code>ownedMembership</code>, which must be an <code>ActionUsage</code>." (Previously it had been implemented as the `sourceFeature` of the `succession` of the `TransitionUsage`.)
2. Revises `SuccessionAsUsageAdapter::addSourceEnd` to always set the `sourceFeature` of the `succession` of a `TransitionUsage` to the `source` of the `TransitionUsage`.
3. Adds a `computeSource` transformation to `TransitionUsageAdapter`, which physically adds an alias `Membership` to the "previous feature" of a `TransitionUsage`, so that this becomes …

ST6RI-699 Problem with the setting of the source feature of the transitionLink of a TransitionUsage

---

org.omg.sysml.interactive/src/org/omg/sysml/interactive/SysMLInteractive.java
org.omg.sysml.interactive/src/org/omg/sysml/interactive/SysMLInteractiveHelp.java
org.omg.sysml.jupyter.kernel/src/main/java/org/omg/sysml/jupyter/kernel/SysMLKernel.java
org.omg.sysml.jupyter.kernel/src/main/java/org/omg/sysml/jupyter/kernel/magic/Help.java

This pull request adds a new `%help` command to the Jupyter SysML v2 kernel. Without an argument, this command prints a list of all available magic commands (this its particularly useful new capability). If given a command name (with or without the initial `%`) as its argument, it prints the help information for that command (i.e., `%help`_`cmd`_ produces the same result as _`%cmd`_` -h`.

ST6RI-681 Add %help command to Jupyter

---

org.omg.sysml/src/org/omg/sysml/delegate/AnalysisCaseDefinition_resultExpression_SettingDelegate.java
org.omg.sysml/src/org/omg/sysml/delegate/AnalysisCaseUsage_resultExpression_SettingDelegate.java

Fixed the derivations of `resultExpression` in `AnalysisCaseDefinition_resultExpression_SettingDelegate` and `AnalysisCaseUsage_resultExpression_SettingDelegate` to be consistent with the specification.

ST6RI-704 Derivations of resultExpression for AnalysisCaseDefinition and AnalysisCaseUsage are incorrect

---

org.omg.sysml/src/org/omg/sysml/delegate/AnalysisCaseUsage_resultExpression_SettingDelegate.java

Corrects `AnalysisCaseUsage_resultExpression_SettingDelegate` by replacing the erroneous cast of the `owner` parameter to `AnalysisCaseDefinition` with a cast to `AnalysisCaseUsage`.

ST6RI-708 Error in AnalysisCaseUsage_resultExpression_SettingDelegate

---

org.omg.sysml/syntax-gen/org/omg/sysml/lang/sysml/impl/FramedConcernMembershipImpl.java
org.omg.sysml/syntax-gen/org/omg/sysml/lang/sysml/impl/RequirementConstraintMembershipImpl.java
org.omg.sysml/syntax-gen/org/omg/sysml/lang/sysml/impl/RequirementVerificationMembershipImpl.java
org.omg.sysml/syntax-gen/org/omg/sysml/lang/sysml/impl/StateSubactionMembershipImpl.java
org.omg.sysml/syntax-gen/org/omg/sysml/lang/sysml/impl/TransitionFeatureMembershipImpl.java
org.omg.sysml/syntax-gen/org/omg/sysml/lang/sysml/impl/TriggerInvocationExpressionImpl.java

1. The `kind` properties of the following metaclasses have enumeration types, but no default in the MOF abstract syntax model, even though they also have a multiplicity lower bound of 1:
* `RequirementConstraintMembership`
* `TriggerInvocationMembership`
* `StateSubactionMembership`
* `TransitionFeatureMembership`
However Eclipse still normally generates a `KIND_EDEFAULT` constant for these properties in the corresponding implementation classes that is set to the first enumeration literal of the corresponding type. This means that the XMI generated for these relationships did not include a `kind` value in the case it was one of these defaults. This pull request updates these implementation classes so that `KIND_EDEFAULT` is set to `null`. As a result, `kind` is always serialized in XMI …

ST6RI-707 Defaults are wrong for various "kind" properties

---

sysml.library/Systems Library/StandardViewDefinitions.sysml

Implementation of the resolution of OMG Issue [SYSML2-293](https://issues.omg.org/issues/SYSML2-291). In particular the ViewDefinition `CaseView` is removed from standard library `StandardViewDefinitions.sysml`.

ST6RI-713 Resolution from SysML v2 FTF Ballot #3

---

kerml/src/examples/KerML Spec Annex A Examples/A-2-Atoms.kerml
kerml/src/examples/KerML Spec Annex A Examples/A-2-ModelingInstances.kerml
kerml/src/examples/KerML Spec Annex A Examples/A-3-2-WithoutConnectors.kerml
kerml/src/examples/KerML Spec Annex A Examples/A-3-3-OneToOneConnectors.kerml
kerml/src/examples/KerML Spec Annex A Examples/A-3-4-OneToUnrestrictedConnectors.kerml
kerml/src/examples/KerML Spec Annex A Examples/A-3-5-TimingForStructures.kerml
kerml/src/examples/KerML Spec Annex A Examples/A-3-6-Sequences.kerml
kerml/src/examples/KerML Spec Annex A Examples/A-3-7-DecisionsAndMerges.kerml
kerml/src/examples/KerML Spec Annex A Examples/A-3-8-ChangingFeatureValues.kerml

This pull request adds, under `kerml/examples/KerML Annex A Examples`, models used as examples in Annex A: Model Execution of the KerML Specification:
- `A-2-Atoms.kerml`
- `A-2-ModelingInstances.kerml`
- `A-3-2-WithoutConnectors.kerml`
- `A-3-3-OneToOneConnectors.kerml`
- `A-3-4-OneToUnrestrictedConnectors.kerml`
- `A-3-5-TimingForStructures.kerml`
- `A-3-6-Sequences.kerml`
- `A-3-7-DecisionsAndMerges.kerml`
- `A-3-8-ChangingFeatureValues.kerml`
It is expected that these models will be included as informative artifacts with the finalized 1.0 specification.

ST6RI-711 Example models from KerML Spec Annex A

---

org.omg.sysml.xtext/src/org/omg/sysml/xtext/validation/SysMLValidator.xtend

This PR implements the check for the constraint `validateAssertConstraintUsageReference`, which is included in the resolution to issue [SYSML2-28](https://issues.omg.org/issues/SYSML2-28) approved in FTF Ballot 6, but was accidentally left out of PR #506.

ST6RI-709 (Update) Resolutions from SysML v2 FTF Ballot #6

---

kerml/src/examples/Simple Tests/Behaviors.kerml
kerml/src/examples/Simple Tests/Expressions.kerml
org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/parsing/ParsingTests_Behaviors.kerml.xt
org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/parsing/ParsingTests_Expressions.kerml.xt
org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/validation/Redefinition_DirectionConformance_invalid.kerml.xt
org.omg.kerml.xtext/src/org/omg/kerml/xtext/validation/KerMLValidator.xtend

This PR corrects `KerMLValidator` so that the`validateRedefinitionDirectionConformance` constraint is checked on implicit as well as explicit redefinitions. In particular, it will be checked for implicit redefinitions of parameters which will, for example, catch the following validation error that was not caught before:
```
behavior A {
in x;
}
behavior B {
out y; // Fails validation
}
```

ST6RI-726 validateRedefinitionDirectionConformance not checked for implicit Redefinitions

---

org.omg.sysml/src/org/omg/sysml/adapter/ConcernUsageAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/TypeAdapter.java
org.omg.sysml/src/org/omg/sysml/util/ImplicitGeneralizationMap.java

1. The semantic constraint `checkConcernUsageFramedConcernSpecialization` in the SysML v2 Specification only requires that framed concerns (i.e., concern usages owned by a requirement definition or usage via a framed concern membership) specialize `Requirements::RequirementsCheck::concerns`. This PR corrects a bug that previously resulted in all concern usages nested in requirement definitions or usages, not just framed concerns, implicitly specializing `Requirements::RequirementsCheck::concerns`. 
2. The PR also corrects a bug in `TypeAdapter::removeUnnecessaryImplicitGeneralTypes` that prevented the removal of some unnecessary implicit specializations.

ST6RI-712 Implicit specialization of non-framed concern usages is wrong

---

org.omg.sysml/syntax-gen/org/omg/sysml/lang/sysml/impl/PortUsageImpl.java
sysml/src/examples/Simple Tests/PartTest.sysml

In the SysML v2 Specification, the `validatePortUsageIsReference` constraint only requires a `PortUsage` to be referential if it is not a feature of a `PortDefinition` or `PortUsage`. This PR corrects the implementation of `PortUsageImpl::isComposite` which previously always returned `false`, even if the port was a feature of a port definition or usage. With this correction, a `PortUsage` nested in a `PortDefinition` or `PortUsage` is composite by default and only referential if declared with the **`ref`** keyword.

ST6RI-714 PortUsage::isComposite is implemented incorrectly

---

org.omg.sysml.xpect.tests/src/org/omg/sysml/xpect/tests/simpletests/ViewTest.sysml.xt
org.omg.sysml.xpect.tests/src/org/omg/sysml/xpect/tests/validation/invalid/ViewRendering_invalid.sysml.xt
org.omg.sysml.xtext/src/org/omg/sysml/xtext/validation/SysMLValidator.xtend
org.omg.sysml/src/org/omg/sysml/adapter/RenderingUsageAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/ViewUsageAdapter.java
org.omg.sysml/src/org/omg/sysml/util/ImplicitGeneralizationMap.java
sysml/src/examples/Simple Tests/ViewTest.sysml

1. This PR corrects the implicit redefinition of a `RenderingUsage` that is a view rendering of a `ViewDefinition` or `ViewUsage` (i.e., that is owned via a `ViewRenderingMembership`). Previously, the implemented gave a view rendering implicit redefinitions of the view renderings of any view definitions or usages specialized by the containing view definition or usage. This has now been changed to conform to the SysML v2 Specification, which requires that view rendering directly redefine `Views::View::viewRendering`.
2. The PR also corrects the checking of the `validateViewDefinitionOnlyOneViewRendering` and `validateViewUsageOnlyOneViewRendering`, so that a `ViewDefinition` or `ViewUsage` can have owned `RedefinitionUsages` other than its (at most) one view rendering.

ST6RI-719 View rendering redefinition is incorrect

---

org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VDefault.java

The visualizer rendered the unnamed memberships, which are typically created by InitialNodeMember such as `first xxx;`. So it looked actions are rendered in a duplicated manner.  This PR lets the visualizer ignore such memberships.

[ST6RI-729] Do not render unnamed alias memberships

---

org.omg.sysml/src/org/omg/sysml/delegate/Type_input_SettingDelegate.java
org.omg.sysml/src/org/omg/sysml/delegate/Type_output_SettingDelegate.java
org.omg.sysml/syntax-gen/org/omg/sysml/lang/sysml/impl/TypeImpl.java

1. Previously, `TypeImpl::directionOf` was implemented to return `FeatureDirectionKind::INOUT` in the case that the `Type` was conjugated and the `originalDirection` of the given `feature` was not `IN` or `OUT`. This has been corrected so that the method returns the `originalDirection` in this case (that is, it returns `null` if the `originalDirection` is `null` and `INOUT` if the `originalDirection` is INOUT).
2. Updated `Type_input_SettingDelegate` and `Type_output_SettingDelegate` so that `ownedFeatures` with the relevant `direction` are returned, even if the `Type` is conjugated.

ST6RI-721 Implementation of Type::directionOf is incorrect for conjugation

---

sysml.library/Kernel Libraries/Kernel Function Library/BaseFunctions.kerml
sysml.library/Kernel Libraries/Kernel Function Library/DataFunctions.kerml
sysml.library/Kernel Libraries/Kernel Function Library/ScalarFunctions.kerml
sysml.library/Kernel Libraries/Kernel Semantic Library/Clocks.kerml
sysml.library/Kernel Libraries/Kernel Semantic Library/ControlPerformances.kerml
sysml.library/Kernel Libraries/Kernel Semantic Library/Links.kerml
sysml.library/Kernel Libraries/Kernel Semantic Library/Observation.kerml
sysml.library/Kernel Libraries/Kernel Semantic Library/Occurrences.kerml
sysml.library/Kernel Libraries/Kernel Semantic Library/Performances.kerml
sysml.library/Kernel Libraries/Kernel Semantic Library/SpatialFrames.kerml
sysml.library/Kernel Libraries/Kernel Semantic Library/Transfers.kerml

This PR implements resolutions of issues from KerML FTF Ballot 3 that called for updates to library models.
Resolutions of the following issues are implemented in this PR:
- [KERML-38](https://issues.omg.org/issues/KERML-38) Binary association ends always unique
- [KERML-42](https://issues.omg.org/issues/KERML-42) Occurrences can be data values
- [KERML-43](https://issues.omg.org/issues/KERML-43) Performances can be objects, behaviors can be structures
- [KERML-56](https://issues.omg.org/issues/KERML-56) Universal features can have many values
- [KERML-77](https://issues.omg.org/issues/KERML-77) Problems with IfThenElsePerformance
- [KERML-88](https://issues.omg.org/issues/KERML-88) BaseFunctions::',' has a bad parameter declaration
- [KERML-188](https://issues.omg.org/issues/KERML-188) …

ST6RI-722 Model library updates from KerML FTF Ballot #3

---

org.omg.sysml/src/org/omg/sysml/adapter/TypeAdapter.java
sysml.library/Domain Libraries/Geometry/SpatialItems.sysml
sysml.library/Systems Library/Actions.sysml
sysml.library/Systems Library/Connections.sysml
sysml.library/Systems Library/Views.sysml

This PR implements resolutions of issues from SysML v2 FTF Ballot 9 that called for updates to library models. In addition, it makes a further revision to `TypeAdapter::removeUnnecessaryImplicitGeneralTypes` (as already revised in PR #514) to ensure removal of implict general types that are the identical to explicit general types.
Resolutions of the following issues are implemented in this PR:
- [SYSML2-79](https://issues.omg.org/issues/SYSML2-79) View::viewpointSatisfactions should subset viewpointChecks and checkedConstraints
- [SYSML2-83](https://issues.omg.org/issues/SYSML2-83) Narrow down return types of SpatialItem::PositionOf and ::CurrentPositionOf
- [SYSML2-102](https://issues.omg.org/issues/SYSML2-102) Semantic constraint for target of AssignmentActionUsage is missing
- …

ST6RI-724 Model library updates from SysML v2 FTF Ballot #9

---

sysml.library/Domain Libraries/Quantities and Units/Time.sysml

In order to avoid a warning caused by the implementation of the resolution to KERML-56 (in PR #520), the declaration of `Time::universalClock` in the Quantities and Units Library has been changed from binding to `Clocks::universalClock` to subsetting it. This is consistent with the proposed resolution to 
- [SYSML2-182](https://issues.omg.org/issues/SYSML2-182) Universal features can have many value
However, this resolution has not yet been approved by the SysML v2 FTF, so it must be considered preliminary.

ST6RI-724 (Update) Model library updates from SysML v2 FTF Ballot #9

---

org.omg.sysml.execution/src/org/omg/sysml/execution/expressions/ExpressionEvaluator.java
org.omg.sysml.interactive.tests/src/org/omg/sysml/interactive/tests/ExpressionEvaluationTest.java
org.omg.sysml.xpect.tests/library.domain/Analysis/TradeStudies.sysml
org.omg.sysml.xpect.tests/src/org/omg/sysml/xpect/tests/simpletests/ConnectionTest.sysml.xt
org.omg.sysml/src/org/omg/sysml/adapter/FeatureAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/InvocationExpressionAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/TypeAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/UsageAdapter.java
org.omg.sysml/src/org/omg/sysml/util/TypeUtil.java
sysml.library/Domain Libraries/Analysis/TradeStudies.sysml
sysml/src/examples/Analysis Examples/Dynamics.sysml
sysml/src/examples/Simple Tests/ConnectionTest.sysml

1. Corrects `FeatureAdapter::isComputeRedefinitions` so that implicit redefinitions are added even if a `Feature` already has `ownedRedefinitions`, consistent with the rules for implied redefinitions per the specifications.
* Except that, for now, implicit redefinitions are still _not_ added for parameters that already have `ownedRedefinitions`. See also 
* [KERML-308 checkFeatureParameterRedefinition fails for named-argument invocations](https://issues.omg.org/issues/KERML-308)
2. Removes the special handling of the redefinition of subject parameters, in which a subject will redefine the subject of a supertype, regardless of its position in the list of parameters. Instead, subject parameter redefinition is handled by the normal rule for implied redefinitions of parameters in order, per …

ST6RI-727 Implicit redefinitions should be added even if there are owned redefinitions

---

org.omg.sysml.interactive.tests/src/org/omg/sysml/interactive/tests/ModelLevelEvaluationTest.java
org.omg.sysml/src/org/omg/sysml/expressions/LibraryFunctionFactory.java
org.omg.sysml/src/org/omg/sysml/expressions/functions/DataFunction.java
org.omg.sysml/src/org/omg/sysml/expressions/functions/ExcludesFunction.java
org.omg.sysml/src/org/omg/sysml/expressions/functions/ListRangeFunction.java

This PR adds two additional model-level evaluable function implementations, under `org.omg.sysml.expressions.functions`.
1. `ListRangeFunction` implements the _range construction operator_ `'..'`. An expression of the form _`e1`_`...`_`e2`_, in which _`e1`_ and _`e2`_ evaluate to integers, results in an ordered sequence of a range of sequential integers from the value of _`e1`_ to the value of _`e2`_, inclusive. For example, `1..3` evaluates to the sequence `(1, 2, 3)`. If the value of _`e1`_ is greater than the value of _`e2`_, then the result is the empty sequence.
2. `ExcludesFunction` implements the `SequenceFunctions::excludes` function. This function tests whether a value is _excluded_ from a sequence. For example, `excludes(1..3, 2)` is false, while `excludes(1..3, 0)` is true. It …

ST6RI-731 Model-level evaluation of the list range construction operator

---

sysml.library/Kernel Libraries/Kernel Semantic Library/Clocks.kerml
sysml.library/Kernel Libraries/Kernel Semantic Library/KerML.kerml
sysml.library/Kernel Libraries/Kernel Semantic Library/Objects.kerml
sysml.library/Kernel Libraries/Kernel Semantic Library/Observation.kerml
sysml.library/Kernel Libraries/Kernel Semantic Library/Occurrences.kerml
sysml.library/Kernel Libraries/Kernel Semantic Library/SpatialFrames.kerml

This PR implements resolutions of issues from KerML FTF Ballot 4 that called for updates to library models.
*Note:* This PR is based off of branch ST6RI-736 (see PR #527).
Resolutions of the following issues are implemented in this PR:
[KERML-25](https://issues.omg.org/issues/KERML-25) Reflective KerML abstract syntax model has inconsistencies
[KERML-44](https://issues.omg.org/issues/KERML-44) Spatial links can be occurrences
[KERML-49](https://issues.omg.org/issues/KERML-49) Some readonly features are intended to have changing values
[KERML-158](https://issues.omg.org/issues/KERML-158) InsideOf association end feature redefines cross feature
[KERML-231](https://issues.omg.org/issues/KERML-231) LinkObject disjointness is redundant
Resolution of the following library-related issue did not …

ST6RI-734 Model-library-related Resolutions from KerML FTF Ballot #4

---

sysml.library/Domain Libraries/Quantities and Units/ISQSpaceTime.sysml
sysml.library/Systems Library/SysML.sysml

This PR implements resolutions of issues from SysML v2 FTF Ballot 10 that called for updates to library models.
**Note:** This PR is based off of branch ST6RI-736 (see PR #527).
Resolution of the following issue is implemented in this PR:
- [SYSML2-80](https://issues.omg.org/issues/SYSML2-80) Reflective SysML abstract syntax model has inconsistencies
Resolution of the following issue was partially implemented in PR #525 and is completed in this PR:
- [SYSML2-182](https://issues.omg.org/issues/SYSML2-182) Universal features can have many values
Resolution of the following issue was previously implemented in PR #525:
- [SYSML2-552](https://issues.omg.org/issues/SYSML2-552) Errors in the TradeStudy domain model
Resolutions of the following issues did not require a model library update:
- …

ST6RI-735 Model-library related issue resolutions from SysML v2 Ballot #10

---

org.omg.kerml.xpect.tests/library/KerML.kerml
org.omg.kerml.xpect.tests/library/Objects.kerml
org.omg.kerml.xpect.tests/library/Occurrences.kerml
org.omg.kerml.xpect.tests/library/Performances.kerml
org.omg.kerml.xpect.tests/library/Transfers.kerml
org.omg.kerml.xtext/src/org/omg/kerml/xtext/validation/KerMLValidator.xtend
org.omg.sysml.xpect.tests/library.kernel/KerML.kerml
org.omg.sysml.xpect.tests/library.kernel/Objects.kerml
org.omg.sysml.xpect.tests/library.kernel/Occurrences.kerml
org.omg.sysml.xpect.tests/library.kernel/Performances.kerml
org.omg.sysml.xpect.tests/library.kernel/Transfers.kerml
org.omg.sysml.xpect.tests/src/org/omg/sysml/xpect/tests/simpletests/ConnectionTest.sysml.xt
org.omg.sysml.xpect.tests/src/org/omg/sysml/xpect/tests/validation/invalid/FlowConnectionUsage_Invalid.sysml.xt
sysml.library/Kernel Libraries/Kernel Data Type Library/.meta.json
sysml.library/Kernel Libraries/Kernel Data Type Library/.project.json
sysml.library/Kernel Libraries/Kernel Data Type Library/Collections.kerml
sysml.library/Kernel Libraries/Kernel Data Type Library/VectorValues.kerml
sysml.library/Kernel Libraries/Kernel Function Library/.meta.json
sysml.library/Kernel Libraries/Kernel Function Library/.project.json
sysml.library/Kernel Libraries/Kernel Semantic Library/.meta.json
sysml.library/Kernel Libraries/Kernel Semantic Library/.project.json
sysml.library/Kernel Libraries/Kernel Semantic Library/Objects.kerml
sysml.library/Kernel Libraries/Kernel Semantic Library/Occurrences.kerml
sysml.library/Kernel Libraries/Kernel Semantic Library/Performances.kerml
sysml.library/Kernel Libraries/Kernel Semantic Library/Transfers.kerml
sysml/src/examples/Simple Tests/ConnectionTest.sysml

This PR implements resolutions of issues from KerML FTF Ballot 5 that called for updates to library models.
Resolutions of the following issues are implemented in this PR:
- [KERML-45](https://issues.omg.org/issues/KERML-45) LinkObject is irreflexive
- [KERML-46](https://issues.omg.org/issues/KERML-46) Intersection missing for some multiple specializations
- [KERML-120](https://issues.omg.org/issues/KERML-120) FlowTransferBefore needs end feature declarations
In addition, the `.meta.json` and `.project.json` files in the model library directories have been updated to reflect the new normative KerML URI `https://www.omg.org/spec/KerML/240201` and the versions have been updated to `1.0.0-beta2`.

ST6RI-739 Model-library-related issues from KerML FTF Ballot #5

---

sysml.library/Domain Libraries/Analysis/.meta.json
sysml.library/Domain Libraries/Analysis/.project.json
sysml.library/Domain Libraries/Cause and Effect/.meta.json
sysml.library/Domain Libraries/Cause and Effect/.project.json
sysml.library/Domain Libraries/Geometry/.meta.json
sysml.library/Domain Libraries/Geometry/.project.json
sysml.library/Domain Libraries/Metadata/.meta.json
sysml.library/Domain Libraries/Metadata/.project.json
sysml.library/Domain Libraries/Quantities and Units/.meta.json
sysml.library/Domain Libraries/Quantities and Units/.project.json
sysml.library/Domain Libraries/Requirement Derivation/.meta.json
sysml.library/Domain Libraries/Requirement Derivation/.project.json
sysml.library/Systems Library/.meta.json
sysml.library/Systems Library/.project.json
sysml.library/Systems Library/VerificationCases.sysml
sysml/src/examples/Vehicle Example/SysML v2 Spec Annex A SimpleVehicleModel.sysml
sysml/src/validation/03-Function-based Behavior/3c-Function-based Behavior-structure mod-2.sysml

This PR implements resolutions of issues from SysML v2 FTF Ballot 11 that called for updates to library models.
Resolution of the following issue is implemented in this PR:
- [SYSML2-158](https://issues.omg.org/issues/SYSML2-158) Example FrontAxle definition
- [SYSML2-634](https://issues.omg.org/issues/SYSML2-634) VerificationCase::subVerificationCases is typed incorrectly
In addition, the `.meta.json` and `.project.json` files in the model library directories have been updated to reflect the new normative SysML URI `https://www.omg.org/spec/SysML/240201` and the versions have been updated to `2.0.0-beta2`. KerML library projects are now required to be version `1.0.0-beta2`, as will be implemented in PR #541.

ST6RI-741 Model-library/example-related issues from SysML v2 FTF Ballot #11

---

org.omg.sysml/src/org/omg/sysml/adapter/LifeClassAdapter.java

As part of the underlying semantics for individuals, every individual definition is required to by the constraint `validateOccurrenceDefinitionLifeClass` to have "exactly one `ownedMember` that is a `LifeClass`". Further, the constraint `checkLifeClassOccurrenceSpecialization` requires that “A `LifeClass` must specialize its `individualDefinition`." However, do to a bug in the `LifeClassAdapter`, this implicit specialization was not being added. This PR fixes that bug.

ST6RI-742 LifeClass implicit specialization is not correct

---

org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VCompartment.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VStructure.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/Visitor.java

As the current visualizer uses textual notation to print ends in compartment, it may show cluttered text in ends such as `start` and `done` actions in successions.  This PR fixes this issue by making proper names from the referenced features.

ST6RI-744 Properly show ends in particular start or done actions (PlantUML)

---

org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/InheritKey.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/PRelation.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/SysML2PlantUMLText.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VDefault.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VPath.java

Mainly due to my mistakes, some inherited references were not correctly rendered with `SHOWINHERITED` style and this PR fixes those issues. 
Notice that ST6RI-745 branches out from ST6RI-744.  So it contains the fixes in ST6RI-744 as well.

ST6RI-745 Inherited references are not properly rendered (PlantUML)

---

org.omg.sysml/syntax-gen/org/omg/sysml/lang/sysml/impl/LibraryPackageImpl.java

The implementation of deterministic UUIDs for standard library packages in PR #457 inadvertently caused the `elementId` property of standard library packages to not be serialized in XMI. This PR fixes that bug. (Note that this bug did _not_ effect serialization to JSON.)

ST6RI-750 The elementId is not being serialized in XMI for LibraryPackages

---

.mvn/extensions.xml

The `org.eclipse.equinox.common` plugin was updated to version 3.19.0 on 8 March 2024. Unlike previous versions, this new version was compiled using Java 17. The Maven `tycho-build` extension indirectly depends on this plugin, causing the new version to be loaded during a Maven build. At this time, our Maven build must run under a Java 11 JRE. As a result, the new `org.eclipse.equinox.common` version caused the build to fail with the error:
> Exception in thread "main" java.lang.UnsupportedClassVersionError: org/eclipse/core/runtime/IProgressMonitor has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
To work around this for the time being, this PR removes the `tycho-build` …

ST6RI-755 Fix Maven build due to the update of org.eclipse.equinox.common

---

org.omg.sysml/src/org/omg/sysml/adapter/UsageAdapter.java

After the 2024-02 release, bindings of enumeration features of metadata usages of metadata definitions from library models, such as
```
part p {
@ModelingMetadata::StatusInfo { 
status = ModelingMetadata::StatusKind::tbd; // WARNING
}
}
```
began causing "Bound features should have conforming types" warnings in the Jupyter environment. This did not happen in the Eclipse editor.
These warnings were caused by the implicit typing of the enumerated value not being properly set to its containing enumeration definition. The typing was only being established when a full transformation was done on the enumerated value declaration. In the Eclipse environment, a full transformation is done on the entire contents of a library model resource when it is read into memory. This is not the case, however, …

ST6RI-749 Bindings with the standard library metadata causes a warning only in Jupyter environment

---

org.omg.kerml.xtext/src/org/omg/kerml/xtext/scoping/KerMLScope.xtend
org.omg.sysml/src/org/omg/sysml/adapter/CalculationDefinitionAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/CalculationUsageAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/CaseDefinitionAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/CaseUsageAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/ConstraintDefinitionAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/ConstraintUsageAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/DefinitionAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/ExpressionAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/FunctionAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/NamespaceAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/RequirementDefinitionAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/RequirementUsageAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/TypeAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/UsageAdapter.java
org.omg.sysml/src/org/omg/sysml/delegate/CaseDefinition_subjectParameter_SettingDelegate.java
org.omg.sysml/src/org/omg/sysml/delegate/CaseUsage_subjectParameter_SettingDelegate.java
org.omg.sysml/src/org/omg/sysml/delegate/RequirementDefinition_subjectParameter_SettingDelegate.java
org.omg.sysml/src/org/omg/sysml/delegate/RequirementUsage_subjectParameter_SettingDelegate.java
org.omg.sysml/src/org/omg/sysml/util/NamespaceUtil.java
org.omg.sysml/src/org/omg/sysml/util/TypeUtil.java
org.omg.sysml/src/org/omg/sysml/util/UsageUtil.java

Currently, there are three cases in which elements are still being physically added to the parse tree (rather than cached in adapters like is done for implicit relationships), when they are not declared explicitly in a model: result parameters for expressions, subject parameters for requirements and cases and objectives for cases. This is not actually called for in the specifications, but is still necessary in order for implied redefinitions to be added correctly in the case of multiple specializations. 
For example, in the following model:
```
analysis def A {
subject s;
objective o;
return r;
}
part context {
part p {
v = a.v;
o = a.o;
r = a.r;
}
analysis a : A {
// subject added that redefines s.
// objective added that redefines o.
// return parameter added that redefines r.
}
}
``` …

ST6RI-751 References to result parameters, subject parameters and objectives do not always resolve correctly

---

org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/SysML2PlantUMLText.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VCompartment.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VTraverser.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/Visitor.java

he standard library elements are rendered even without SHOWLIB and SHOWINHERITED style if they are referred by some connectors.  Also this PR limits the maximum number of elements to be processed, which is useful for rendering with `SHOWLIB` style.

ST6RI-748: Standard library elements are rendered without SHOWLIB and SHOWINHERITED styles (PlantUML)

---

org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/InheritKey.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/SysML2PlantUMLText.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VActionMembers.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VComposite.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VDefault.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VPath.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VStructure.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VTree.java

So far, the visualizer wrongly assumed feature chains refer to features directly or indirectly owned by the owning feature of the feature chains.  Therefore, the example below was incorrectly rendered:
```
action a1 {
first a3.a31 then a11;
action a11;
}
action a3 {
action a31;
}
```
as

ST6RI-759: Feature chains referring to features that do not belong to the owning features are not correctly rendered (PlantUML)

---

org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VBehavior.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/Visitor.java

This PR mainly fixes the issue that `%viz Actions::AcceptAction::aState::aTransition` crashes PlantUML.  This is caused by  inappropriate newline in name.  I also refactored SendActionUsage and AcceptActionUsage rendering because they excessively used getText() and may contain cluttered text.

ST6RI-756: `%viz Actions::AcceptAction::aState::aTransition` in Jupyter causes a PlantUML crash (PlantUML)

---

org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/SysML2PlantUMLText.java

This PR fixes the issue that `«variation»` is missing in a definition with variation.

ST6RI-761: Variations of definitions are not rendered (PlantUML)

---

org.omg.sysml.jupyter.installer/.classpath
org.omg.sysml.jupyter.installer/.settings/org.eclipse.jdt.core.prefs
org.omg.sysml.jupyter.installer/install.bat
org.omg.sysml.jupyter.installer/install.sh
org.omg.sysml.jupyter.jupyterlab/.classpath
org.omg.sysml.jupyter.jupyterlab/.settings/org.eclipse.jdt.core.prefs
org.omg.sysml.jupyter.jupyterlab/package.json

This PR updates the Jupyter deployment to upgrade the version of JupyterLab from 2.x to 3.x, which allows the use of Node.js version 16.x. This is then consistent with the setting of Node.js version 16.20.1 in Maven build script. This only affects the installation of the JupyterLab extension for SysML, not the kernel, via the following changes:
1. `org.omg.sysml.jupyter.jupyterlab/package.json` – The version for the dependency on `jupyterlab/application` changes from `2.x` to `3.x`.
2. `org.omg.sysml.jupyter.installer/install.sh` and `install.bat` – In the `conda install` command, the version for `jupyterlab` changes from `2.*` to `3.*` and the version for `nodejs` changes from `15.*` to `<17`.
**Note.** The Jupyter extension installation still uses `jupyterlab labextension`, which is …

ST6RI-765 Update to JupyterLab version 3.x in the Jupyter deployment

---

org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/SysML2PlantUMLStyle.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/SysML2PlantUMLText.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VPath.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VTraverser.java

Since `start` action is a standard library element having lots of features, the visualizer needed to process them, exceeding the limit of elements that can be processed, even though the `SHOWLIB` style is not selected.  This PR fixes the issue by preventing `VPath` from traversing standard library elements if `SHOWLIB` style is not specified.
This PR also adds a style configuration to `SuccessionFlowConnectionUsage` to properly render it and an error message shown in cases when the visualizer still hits the element limit.

ST6RI-771 With `start` action, some flow connections are not rendered properly (PlantUML)

---

org.omg.sysml/src/org/omg/sysml/delegate/setting/CaseDefinition_actorParameter_SettingDelegate.java
org.omg.sysml/src/org/omg/sysml/delegate/setting/CaseUsage_actorParameter_SettingDelegate.java
org.omg.sysml/src/org/omg/sysml/delegate/setting/RequirementDefinition_actorParameter_SettingDelegate.java
org.omg.sysml/src/org/omg/sysml/delegate/setting/RequirementDefinition_stakeholderParameter_SettingDelegate.java
org.omg.sysml/src/org/omg/sysml/delegate/setting/RequirementUsage_actorParameter_SettingDelegate.java
org.omg.sysml/src/org/omg/sysml/delegate/setting/RequirementUsage_stakeholderParameter_SettingDelegate.java
org.omg.sysml/src/org/omg/sysml/util/TypeUtil.java

According to the Beta 2 version of the SysML v2 specification, the derivations of the `actorParameter` and `stakeholderParameter` properties for `RequirementDefinitions` and `RequirementUsages` and of `actorParameter` for `CaseDefinitions` and `CaseUsages` are supposed to included both owned and inherited actors and stakeholders. Previously, however, the implementation only returned owned actors and stakeholders. This PR corrects the implementation to be conformant with the specification.

ST6RI-760 Actor and stakeholder property derivations only return owned usages

---

org.omg.kerml.expressions.xtext.ide/META-INF/MANIFEST.MF
org.omg.kerml.expressions.xtext.ui/META-INF/MANIFEST.MF
org.omg.kerml.expressions.xtext/META-INF/MANIFEST.MF
org.omg.kerml.owl.ide/META-INF/MANIFEST.MF
org.omg.kerml.owl.ui/META-INF/MANIFEST.MF
org.omg.kerml.owl/META-INF/MANIFEST.MF
org.omg.kerml.xpect.tests/META-INF/MANIFEST.MF
org.omg.kerml.xtext.ide/META-INF/MANIFEST.MF
org.omg.kerml.xtext.ui/META-INF/MANIFEST.MF
org.omg.kerml.xtext/META-INF/MANIFEST.MF
org.omg.sysml.edit/META-INF/MANIFEST.MF
org.omg.sysml.editor/META-INF/MANIFEST.MF
org.omg.sysml.execution/META-INF/MANIFEST.MF
org.omg.sysml.interactive.tests/META-INF/MANIFEST.MF
org.omg.sysml.interactive/META-INF/MANIFEST.MF
org.omg.sysml.jupyter.kernel/assembly.xml
org.omg.sysml.jupyter.kernel/pom.xml
org.omg.sysml.plantuml.eclipse/META-INF/MANIFEST.MF
org.omg.sysml.plantuml/META-INF/MANIFEST.MF
org.omg.sysml.xpect.tests/META-INF/MANIFEST.MF
org.omg.sysml.xtext.ide/META-INF/MANIFEST.MF
org.omg.sysml.xtext.ui/META-INF/MANIFEST.MF
org.omg.sysml.xtext/META-INF/MANIFEST.MF
org.omg.sysml/META-INF/MANIFEST.MF
pom.xml

This pull request updates the `jupyter-sysml-kernel` project to resolve some minor problems with the new build process introduced in PR #568:
- Modifies `assembly.xml` to incude the `LICENSE-GPL` file in the zipped kernel deployment package.
- Adds a clean step that removes `.jars` from the target/kernel before copying the new shaded `.jar`, preventing `.jars` getting "stuck" in the unzipped kernel directory resulting in multiple `.jars` with different versions in the zipped kernel package.

ST6RI-775 LICENSE-GPL file needs to be packaged in the Jupyter kernel build

---

org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VTraverser.java

Because of my mistake in ST6RI-771 (PR #566), inherited features of non-standard library are wrongly hidden.  So the example below:
```
package TestStdLib {
part def P1 {
part p1;
}
part p : P1 {
part p2;
connect p1 to p2;
}	
}
```
is wrongly rendered as:

ST6RI-778: Inherited elements of non-standard libraries are not shown (PlantUML)

---

org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VPath.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VSSRMembers.java

When the visualizer renders a connector, it also renders inherited features referred by the connector.  However, it may fail to render nested features.  In the example below:
```
package TestInheritedPart2 {
part def Vehicle {
part powerTrain {
part shaft {
port rotation;
}
}
}
part vehicle : Vehicle {
part :>> powerTrain {
part motor {
part shaft {
port rotation;
}
}
bind motor.shaft.rotation = shaft.rotation;
}
}
}
```
rendering just part `vehicle` gives:
which lacks `vehicle.powerTrain.shaft.rotation` even though it is referred to by the binding connector.
This PR also fixes `VSSRMember.isRedefining()` by using `FeatureUtil`.

ST6RI-780: Nested inherited features are not correctly rendered (PlantUML)

---

org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/SysML2PlantUMLStyle.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VAction.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VMixed.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VSequence.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VStateMachine.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VStructure.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VTree.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/Visitor.java

This PR supports rendering multiplicities in nodes.  So far the visualizer renders multiplicities in edges only.  I added three new styles:
- NODEMULTIPLICITY
Show multiplicities in nodes.
- EDGEMULTIPLICITY
Show multiplicities in edges.
- IMPLICITMULTIPLICITY
Show implicit multiplicities as well.  That means even if you do not explicitly specify multiplicities, the visualizer renders default multiplicities.
If you do not specify any styles, view choose proper multiplicity rendering.  For example, `Tree` view shows multiplicities in nodes by default.

ST6RI-781: Show multiplicities in nodes (PlantUML)

---

org.omg.sysml/src/org/omg/sysml/delegate/setting/TransitionUsage_source_SettingDelegate.java
org.omg.sysml/src/org/omg/sysml/util/UsageUtil.java

As reported in OMG issue [SYSML2_-222](https://issues.omg.org/issues/SYSML2_-222), the derivations of the `TransitionUsage::source` and `target` properties given in the specification currently do not support the use of feature chains as the source or target of a transition. However, the derivation for `TransitionUsage::target` as implemented in the Pilot Implementation does already allow the use of feature chains as transition targets. Unfortunately, the implemented derivation of `TransitionUsage::source` did not allow feature chains to be used as transition sources, which was inconsistent.
This PR:
- Updates the implementated derivation of `TransitionUsage::source` so that it also consistently allows feature chains, presupposing the eventual resolution of SYSML2_-222.
- Updates the …

ST6RI-793 Transition source cannot be a feature chain

---

org.omg.kerml.xtext.ui/src/org/omg/kerml/xtext/ui/library/DynamicLibraryIndexProvider.java
org.omg.kerml.xtext/src/org/omg/kerml/xtext/library/LibraryIndex.java
org.omg.kerml.xtext/src/org/omg/kerml/xtext/library/PrecalculatedLibraryIndexProvider.java
org.omg.sysml.interactive/src/org/omg/sysml/interactive/SysMLInteractiveLibraryIndexGenerator.java
org.omg.sysml.xtext.ui/src/org/omg/sysml/xtext/ui/handlers/GenerateLibraryIndex.java

Previously, `LibraryIndex` read and wrote index files without specifying encoding. Therefore, if the default encoding of the JRE was not UTF-8, those files could be corrupted. In a Japanese Windows environment, the default encoding is CP932, and the library index was corrupted because it could not encode all of the Unicode characters used in the SysMLv2 libraries.
This PR updates `LibraryIndex` to use UTF-8 encoding. It also fixes an issue with constructing a proper index filename at PrecalculatedLibraryIndexProvider.getIndexFile(). To convert an EMF URI to a filename, `toFileString()` must be used.

ST6RI-794: Specify UTF-8 encoding to access index files.

---

org.omg.sysml/src/org/omg/sysml/adapter/FeatureAdapter.java
org.omg.sysml/src/org/omg/sysml/delegate/invocation/Feature_effectiveName_InvocationDelegate.java
org.omg.sysml/src/org/omg/sysml/delegate/invocation/Feature_effectiveShortName_InvocationDelegate.java
org.omg.sysml/src/org/omg/sysml/util/FeatureUtil.java

[Feature_effectiveShortName_InvocationDelegate](https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/blob/d20a563968c7b78616ee80481829e0e4f6aee2e1/org.omg.sysml/src/org/omg/sysml/delegate/invocation/Feature_effectiveShortName_InvocationDelegate.java#L43) and [Feature_effectiveName_InvocationDelegate](https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/blob/d20a563968c7b78616ee80481829e0e4f6aee2e1/org.omg.sysml/src/org/omg/sysml/delegate/invocation/Feature_effectiveName_InvocationDelegate.java#L43) cache their result. The caches are stored by the Invocation Delegates and they are never invalideted. This can lead to values getting stuck or possibly even memory leaks.
- Moved `effectiveName` cache from `Feature_effectiveName_InvocationDelegate`to `FeatureAdapter`
- …

ST6RI-796 Leftover caches in InvocationDelegates

---

org.omg.sysml/src/org/omg/sysml/adapter/PortConjugationAdapter.java

This PR corrects a bug causing the `source` and `conjugatedType` fields of `PortConjugation` to not be set. This results int the JSON emitted by the `SysML2JSON` utility to produce empty values for these attributes. They should both be populated with the `conjugatedPortDefinition` of the `PortConjugation`. 
`PortConjugation` is a specialization of the KerML `Conjugation` relationship. The `Conjugation::conjugatedType` property redefines `Relationship::source`. In KerML, a `Conjugation` may or may not be owned by its `conjugatedType`. If it is owned, then its `owningType` must be the same as its `conjugatedType` – but these are still two separate properties. In SysML, `PortConjugation::conjugatedPortDefinition` redefines `Conjugation::owningType`, and a `PortConjugation` must be owned by …

ST6RI-797 PortConjugation elements have no elements listed in the JSON source field

---

org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VPath.java

When rendering `TransitionUsage`, the visualizer uses its `SucessionAsUsage` as a connector.  The code for TransitionUsage to resolve end features was not updated previously, even though the algorithm to resolve end features had been fixed and updated. This PR removed the wrong code that was only used for `TransitionUsage`.

ST6RI-802: TransitionUsages may be wrongly rendered (PlantUML)

---

org.omg.sysml/src/org/omg/sysml/util/ImplicitGeneralizationMap.java

This PR fixes a bug that caused `BindingConnectorAsUsages` to get an implicit subsetting of _`Links::links`_ rather than _`Links::selfLinks`_, which is the correct subsetting for all kinds of `BindingConnectors`. 
`BindingConnectorAsUsage` specializes both `BindingConnector` and `Usage`, but it is the `UsageAdapter` that is selected for use for a `BindingConnectorAsUsage` (because there is no `BindingConnectorAsUsageAdapter` or `BindingConnectorAdapter`). As a result, the `base` value from the `ImplicitGeneralizationMap` is used for a `BindingConnectorAsUsage`, not the `binary` value. Unfortunately, only the `binary` value was set to _`Links::selfLinks`_ with the `base` value being `Links::links`. Since a `BindingConnectorAsUsage` must always be binary anyway, changing the `base` value to …

ST6RI-804 BindingConnctorAsUsages are not given the proper implicit subsetting

---

org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/validation/Specialization_invalid.kerml.xt
org.omg.kerml.xtext/src/org/omg/kerml/xtext/validation/KerMLValidator.xtend

This PR implements the resolution to the following issue that was approved in KerML FTF1 Ballot 3.
- [KERML-43](https://issues.omg.org/issues/KERML-43) Performances can be objects, behaviors can be structures
This resolution introduces two new validation constraints:
-  `validateStructureSpecialization`
-  `validateBehaviorSpecialization`
Together, these two constraints disallow a `Structure` from inheriting from a `Behavior`, and vice versa. However, these validations were not implemented at the time the resolution was approved because, at that time, in SysML v2, a `FlowConnectionDefinition` specialized both `PartDefinition` (a kind of `Structure`) and `ActionDefinition` (a kind of `Behavior`). The new validations would thus have make `FlowConnectionDefinition`.
Resolving this problem …

ST6RI-730 Validation updates from KerML FTF1 Ballot #3

---

org.omg.sysml.xpect.tests/library.systems/Interfaces.sysml
org.omg.sysml.xpect.tests/library.systems/Ports.sysml
sysml.library/Systems Library/Interfaces.sysml
sysml.library/Systems Library/Ports.sysml

This PR implements the resolution to the following issue, as approved in SysML v2 FTF2 Ballot 6.
- [SYSML2_-39](https://issues.omg.org/issues/SYSML2_-39) Semantics of transfers across interfaces
This resolution updates the Systems Library models `Ports.sysml` and `Interfaces.sysml` to specify the semantics of automatically targeting a transfer whose source is a `Port` at one end of an `Interface` to a `Port` at a different end of the `Interface`.

ST6RI-813 Transfers across interfaces (SYSML2_-39)

---

org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/validation/ResultExpressionMembership_Invalid.kerml.xt
org.omg.sysml/src/org/omg/sysml/util/TypeUtil.java

This PR corrects the checking of the `validateFunctionResultExpressionMembership` and `validateExpressionResultExpressionMembership` constraints. These constraints require that a `Function` or `Expression` have at most one owned or inherited `ResultExpressionMembership`. However, the implementation was allowing a `Function` or `Expression` to have inherited `ResultExpressionMemberships` if it had an owned `ResultExpressionMembership` (but it still only allowed one inherited `ResultExpressionMembership` if there was no owned `ResultExpressionMembership`).
The problem was with the utility method `TypeUtil.getResultExpressionMembershipsOf`, which is used to search the supertype hierarchy just for `ResultExpressionMemberships`. This had been implemented to stop searching when a `Type` was …

ST6RI-820 ResultExpressionMembership validation is incorrect

---

kerml/src/examples/KerML Spec Annex A Examples/A-3-5-TimingForStructures.kerml
org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/validation/AssociationTest_EndTypes_invalid.kerml.xt
org.omg.kerml.xtext/src/org/omg/kerml/xtext/validation/KerMLValidator.xtend

This PR implements the resolution to the following issue from KerML FTF2 Ballot 2:
- [KERML_-32](http://issues.omg.org/issues/KERML_-32) Association ends can have more than one type
(This resolution should have been implemented in the 2024-12 release, but it was missed.)
The resolution to this issue adds a new `validateAssociationEndTypes` constraint that requires association end features (or connection end features in SysML) to have exactly one type.

ST6RI-819 Association end type constraint (KERML_-32)

---

org.omg.sysml/src/org/omg/sysml/delegate/setting/ItemUsage_itemDefinition_SettingDelegate.java

This PR implements the resolution to the following issue from SysML v2 FTF2 Ballot 5:
- [SYSML2_-394](http://issues.omg.org/issues/SYSML2_-394) deriveItemUsageItemDefinition is incorrect
(This resolution should have been implemented in the 2024-12 release, but it was missed.)
The resolution to this issue corrects the `deriveItemUsageItemDefinition` constraint so that the `itemDefinitions` of an `ItemUsage` can include KerML `Structures` as well as SysML `ItemDefinitions`.

ST6RI-822 deriveItemUsageItemDefinition (SYSML2_-394)

---

sysml.library/Domain Libraries/Geometry/ShapeItems.sysml
sysml.library/Systems Library/Items.sysml

Updates the Geometry Domain Library model `ShapeItems.sysml` for the resolution to the following SysML v2 FTF2 issue.
- [SYSML2_-471](https://issues.omg.org/issues/SYSML2_-471) Unredefinable shape attributes
Specifically, `radius` on `Circle`, `CircularDisc`, `Sphere`, `CircularCone`, and `CircularCylinder` are made redefinable by moving their declaration bindings to the features they were bound to.  Also, asserted constraints on `Sphere`, `CircularCone`, and `CircularCylinder` are changed to equivalent declaration bindings.

ST6RI-614 Redefinable shape attributes (SYSML2_-471)

---

sysml.library/Kernel Libraries/Kernel Semantic Library/Occurrences.kerml

Updates Kernel Semantic Library model `Occurrences.kerml` for the resolution to this SysML v2 FTF2 issue.
- [KERML_-104](https://issues.omg.org/issues/KERML_-104) Transitivity missing for some time/space associations
Specifically, these features of `Occurrence`: `timeCoincidentOccurrences`, `spaceEnclosedOccurrences`, `spaceTimeEnclosedOccurrences`, `spaceTimeCoincidentOccurrences`, `portionOf`, `timeSliceOf ` (ensures `spaceShotOf ` includes all `timeSliceOf` transitively, due to sufficiency of `snapshots`), `spaceSliceOf`, and `spaceShotOf`.
Also adds to `spaceEnclosedOccurrences` that "smaller" spaces are outside occurrences that are outside their "larger" spaces, similar to existing axioms for time ordering.

ST6RI-821 Transitivity for time/space relations where it is missing (KERML_-104)

---

sysml.library/Kernel Libraries/Kernel Semantic Library/Occurrences.kerml

Updates Kernel Semantic Library model `Occurrences.kerml` for the resolution to this KerML FTF2 issue.
- [KERML_-5](https://issues.omg.org/issues/KERML_-5) isComposite, semantics?
Adds
- Informal semantics (in text) for single "ownership" via composite features (values of composite features cannot be values of other composite features that are not featured by the same composing instance).
- Modeled semantics for the above and for the existing informal "destruction" semantics (values of composite features at the time their composing occurrence end also end at that time):
- Single ownership: Multiplicity [0..1] on a new inverse of `suboccurrences` (`superoccurrence`).
- Destruction: Time coincidence of `endShot` and `endShots` of its `suboccurrences`.

ST6RI-826 isComposite semantics (KERML_-5)

---

org.omg.sysml.xpect.tests/library.domain/Analysis/TradeStudies.sysml
org.omg.sysml.xpect.tests/library.domain/Quantities and Units/Time.sysml
sysml.library/Domain Libraries/Analysis/TradeStudies.sysml
sysml.library/Domain Libraries/Quantities and Units/Time.sysml

This PR updates models from two domain libraries per the resolutions to the following issues approved on SysML v2 FTF2 Ballot 7.
- [SYSML2_-32](https://issues.omg.org/browse/SYSML2_-32) Resolve "TODO" in domain library model Time
- [SYSML2_-248](https://issues.omg.org/browse/SYSML2_-248) Evaluation problem with TradeStudyObjectives
<ins>Analysis Domain LIbrary</ins>
- `TradeStudies.sysml` – Renames the parameter `TradeStudyObjective::fn` to `eval` to avoid a name conflict.
<ins>Quantities and Units Domain Library</ins>
- `Time.sysml` – Removes two "TODO" comments.

ST6RI-832 Domain library models (SYSML2_-32/248)

---

kerml/src/examples/Behavior Examples/TakePicture.kerml
kerml/src/examples/Simple Tests/Expressions.kerml
org.omg.kerml.xpect.tests/library/ControlPerformances.kerml
org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/parsing/ParsingTests_Expressions.kerml.xt
org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/validation/Redefinition_End_Invalid.kerml.xt
org.omg.kerml.xtext/src/org/omg/kerml/xtext/validation/KerMLValidator.xtend
org.omg.sysml.xpect.tests/library.kernel/ControlPerformances.kerml
org.omg.sysml.xpect.tests/library.systems/Actions.sysml
org.omg.sysml.xtext/src/org/omg/sysml/xtext/validation/SysMLValidator.xtend
org.omg.sysml/src/org/omg/sysml/adapter/ActionDefinitionAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/ActionUsageAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/BehaviorAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/FeatureAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/FlowAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/FlowUsageAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/IndexExpressionAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/StepAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/TypeAdapter.java
org.omg.sysml/src/org/omg/sysml/delegate/invocation/Type_allRedefinedFeaturesOf_InvocationDelegate.java
org.omg.sysml/src/org/omg/sysml/util/TypeUtil.java
sysml.library/Kernel Libraries/Kernel Semantic Library/ControlPerformances.kerml
sysml.library/Systems Library/Actions.sysml
sysml/src/examples/Camera Example/PictureTaking.sysml
sysml/src/training/20. Assignment Actions/Assignment Example.sysml

This PR implements some or all of the resolutions of the following issues approved on KerML FTF2 Ballot 5:
- [KERML_-1](http://issues.omg.org/issues/KERML_-1) isEnd of the redefining feature must match isEnd of the redefined feature
- [KERML_-58](http://issues.omg.org/issues/KERML_-58) checkFeatureParameterRedefinition fails for named-argument invocations
- [KERML_-151](http://issues.omg.org/issues/KERML_-151) Corrections to the resolution of KERML_-39
The resolutions of the following related issues had already been previously implemented:
- [KERML_-59](http://issues.omg.org/issues/KERML_-59) OCL for checkFeatureParameterRedefinition is wrong
- [KERML_-146](http://issues.omg.org/issues/KERML_-146) Need to revise derivation of AnnotatingElement::ownedAnnotatingRelationship
- …

ST6RI-828 Operation and Constraint Updates for 2025-02/Beta 3

---

org.omg.sysml.interactive.tests/.launch/Derived Property and Operation Test.launch
org.omg.sysml.interactive.tests/src/org/omg/sysml/interactive/tests/DerivedPropertyAndOperationTest.java
org.omg.sysml/src/org/omg/sysml/delegate/invocation/Element_path_InvocationDelegate.java
org.omg.sysml/src/org/omg/sysml/delegate/invocation/OwningMembership_path_InvocationDelegate.java
org.omg.sysml/src/org/omg/sysml/delegate/invocation/Relationship_path_InvocationDelegate.java
org.omg.sysml/src/org/omg/sysml/delegate/setting/Element_qualifiedName_SettingDelegate.java
org.omg.sysml/syntax-gen/org/omg/sysml/lang/sysml/impl/ElementImpl.java
org.omg.sysml/syntax-gen/org/omg/sysml/lang/sysml/impl/LibraryPackageImpl.java
org.omg.sysml/syntax-gen/org/omg/sysml/lang/sysml/impl/NamespaceImpl.java
org.omg.sysml/syntax-gen/org/omg/sysml/lang/sysml/impl/OwningMembershipImpl.java

This PR implements resolutions to the following issues, as approved in KerML FTF2 Ballot 5 and SysML v2 FTF 2 Ballot 8:
- [KERML_-36](http://issues.omg.org/issues/KERML_-36) KerML Libraries' elements shall have an elementId defined
- [SYSML2_-107](http://issues.omg.org/issues/SYSML2_-107) SysML Libraries' elements shall have an elementId defined
**Paths**
The resolution to KERML_-36 introduces the concept of a "path" for an element that is unique within the composition structure under a specific root namespace. The element path is constructed as follows:
1. If the element has a non-null qualified name, that is used as the path. This means that the UUIDs generated for elements with non-null qualified names will remain unchanged from previous versions of the normative library models.
2. If …

ST6RI-829 Standard model library element IDs (KERML_-36, SYSML2_-107)

---

org.omg.sysml.interactive.tests/src/org/omg/sysml/interactive/tests/ModelLevelEvaluationTest.java
org.omg.sysml/src/org/omg/sysml/delegate/invocation/FeatureReferenceExpression_modelLevelEvaluable_InvocationDelegate.java
org.omg.sysml/src/org/omg/sysml/expressions/ModelLevelExpressionEvaluator.java

The resolution of the following issue, approved in KerML FTF2 Ballot 7 allowed constructor expression to be model-level evaluable.
- [KERML_-224 ](https://issues.omg.org/issues/KERML_-224)Corrections to Ballot 5 resolutions
The update to the `ConstructorExpression::modelLevelEvaluable operation` from this resolution was already implemented. This PR updates `ModelLevelExpressionEvaluator` to actually evaluate constructor expressions.
A constructor expression is parsed as an expression whose `instantiatedType` is instantiated by its `result` parameter, with `argument` expressions bound to appropriate features of the `instantiatedType`. For example, given the (KerML) declaration
```
struct S {
feature a;
feature b;
}
```
then the constructor expression `S(1,2)` is semantically equivalent to …

ST6RI-840 Constructor expression evaluation (KERML_-224)

---

org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/SysML2PlantUMLText.java

By the side effect of the fix by https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/pull/560, `<<variation>>` is rendered for `EnumerationDefinition` because its `isVariation` is true.  However it should not be rendered.  This PR fixes this issue.

ST6RI-837: Do not render <<variation>> for EnumerationDefinition

---

org.omg.sysml/model/KerML_only.uml
org.omg.sysml/model/SysML.ecore
org.omg.sysml/model/SysML.uml
org.omg.sysml/model/kerml.ecore
org.omg.sysml/model/sysml_clean.ecore
org.omg.sysml/syntax-gen/org/omg/sysml/lang/sysml/Type.java
org.omg.sysml/syntax-gen/org/omg/sysml/lang/sysml/impl/SysMLPackageImpl.java
org.omg.sysml/syntax-gen/org/omg/sysml/lang/sysml/impl/TypeImpl.java

This PR implements a proactive update to resolve the following issue, which is to be considered by the future KerML 1.1 RTF.
- [KERML_-230](https://issues.omg.org/issues/KERML_-230)  isCompatibleWith operation needs a return type
The PR updates the operations `Type::isCompatibleWith` and `Feature::isCompatibleWith` to add the missing return type of `Boolean`. The following files in the `org.omg.sysml/model` directory have been updated for this:
- `SysML.uml`
- `KerML_only.uml`
Note that the following files have _not_ been updated:
- `SysML_xmi.uml`
- `SysML_only_xmi.uml`
The following Ecore files have been regenerated, along with the relevant Java files in the `syntax-gen` directory.
- `SysML.ecore`
- `sysml_clean.ecore`
- `kerml.ecore`

ST6RI-841 The isCompatibleWith operation needs a return type

---

org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/SysML2PlantUMLStyle.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/SysML2PlantUMLText.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VCompartment.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VDefault.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VMixed.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VStructure.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VTree.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/Visitor.java

This PR renders shorthand notations for `PerformActionUsage`, `ExhibitStateUsage`, `EventOccurrenceUsage`, and `IncludeUsecase`.  In the example below, we can use just an arrow with `<<perform>>` label from p1 to a0 to render `PerformActionUsage` without rendering a distinct node for it.
```
part p1 {
perform a0;
}
action a0;
```
However, we cannot use this notation if `PerformActionUsage` is referred to by others or if it has its own members, because we cannot properly render this information without a distinct node.  We render a _cumbersome_ notation with a distinct node in such cases.

ST6RI-842: Support shorthand notations (PlantUML)

---

org.omg.sysml/src/org/omg/sysml/adapter/FeatureAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/TransitionUsageAdapter.java
org.omg.sysml/src/org/omg/sysml/adapter/TypeAdapter.java
org.omg.sysml/src/org/omg/sysml/util/ConnectorUtil.java

This PR corrects a bug that can cause an exception when a model is saved to XMI with implicit elements.
In the Beta 3 version of the KerML Specification, the `checkFeatureValueBindingConnector` constraint was updated so that the implied `BindingConnector` for a `FeatureValue` is between the `featureWithValue` and a feature chain consisting of the `value` `Expression` and the `result` of that `Expression` (where previously it had been directly to the `result`). This was implemented in the 2025-02 release (see change to `FeatureAdapter` in PR #638). The target feature chain of the implied `BindingConnector` should have been owned by the `ReferenceSubsetting` relating it to the appropriate `connectorEnd`. Unfortunately, the implementation did not do this, so the owning `Feature` for the …

ST6RI-850 Generating XMI with implicit elements can cause an exception

---

.github/workflows/maven-publish.yml

Configuration has been added on `master` to use GiHub Actions to initiate CI builds on a push to the repository.
This PR adds a release-build workflow, triggered by publishing a release record in the repository or by executing the workflow manually.
This build is different from normal builds in the following ways:
- It skips test execution (it is expected a normal build already ran successfully for this commit before the release is finalized)
- It skips verification of the generated library index (again, it is expected a normal build was already run)
- A Maven version task is executed to remove the -SNAPSHOT version.
Important to note: if the process is executed a second time without changing the base versions, the publish process will fail, as release builds cannot be overwritten in …

ST6RI-849 Configure GitHub Actions for CI builds

---

org.omg.sysml/src/org/omg/sysml/util/TypeUtil.java

This PR corrects a non-conformance of the Pilot Implementation with the KerML Specification on the computation of the `Feature::isCompatibleWith` operation.
The `isCompatibleWith` operation allows a feature to be considered "compatible with" another feature, even if the first feature is not a specialization of the second. This is necessary to allow the implied featuring types of variable features to be considered compatible in certain cases. But, according to the specification, two features can only be compatible in this way if they both have no nested features. Previously, the Pilot Implementation allowed compatibility if at least one of the features had no nested features, but didn't require both to have no features. This PR changes the implementation to conform to the specification. …

ST6RI-847 TypeUtil.isCompatibleWith does not match specification

---

org.omg.sysml/src/org/omg/sysml/util/FeatureUtil.java

This PR fixes a bug in the implementation of `FeatureUtil.canAccess` for checking accessibility when the subsetting feature has no featuring types.

ST6RI-848 Bug in FeatureUtil.canAccess

---

org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VBehavior.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VCase.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VCaseMembers.java
org.omg.sysml.plantuml/src/org/omg/sysml/plantuml/VMixed.java

Since VCase cannot handle actions properly, the model below causes a crash.
```
case c1 {
first start;
then action a;
}
```
This PR fixes this issue and lets the visualizer properly render actions as well as cases.

ST6RI-863 Actions in a case will cause a crash of the visualization (PlantUML)

---

org.omg.sysml/src/org/omg/sysml/adapter/TransitionUsageAdapter.java

This PR fixes a bug that caused spurious validation error markings on conditional successions in the Xtext SysML editor in Eclipse.
For example, in the following model, the source of the conditional succession `s` is implicitly the preceding action `a`:
```
action def A {
action a;
if true than b;
action b;
}
```
Previously, this would initially parse correctly in the Xtext editor without validation errors. But, if it was part of a larger model, then, when a change was made elsewhere in the model, after incremental re-parsing, the source on the conditional succession was not set correctly, resulting in the validation error “Must have at least two related elements”.
A so-called "conditional succession" is actually parsed as a `TransitionUsage`, and an implied source such as above is …

ST6RI-871 Source of a conditional succession not set properly

---

org.omg.sysml/src/org/omg/sysml/delegate/invocation/Membership_isDistinguishableFrom_InvocationDelegate.java

This PR corrects the implementation of `Membership_isDistinguishableFrom_invocationDelegate`.
- Uses `equals` instead of `==` for string comparisons.
- Corrects the test for `memberName == null` to `memberNeme != null`.

ST6RI-868 Coding error in delegate for Membership::isDistinguishableFrom operation

---

org.omg.sysml/src/org/omg/sysml/util/ElementUtil.java

This PR corrects the insertion of implied binding connectors during XMI or JSON export of a model.
For historical reasons, the insertion of binding connectors was previously done before the transformation of the corresponding owning element. However, the implied binding connector of a feature value is owned by the feature that owns the feature value, and that binding connector will not be creating unless the owning feature is transformed first.
This PR updates the method `ElementUtil::transformAll` so that an element and all its owned elements are transformed before any implied elements are inserted, including binding connectors and specializations.

ST6RI-873 Implied binding connectors not generated

---

org.omg.kerml.xpect.tests/library/Transfers.kerml
org.omg.kerml.xtext/src/org/omg/kerml/xtext/validation/KerMLValidator.xtend
org.omg.sysml.xpect.tests/library.kernel/Transfers.kerml
org.omg.sysml.xpect.tests/library.systems/Flows.sysml
org.omg.sysml/src/org/omg/sysml/util/ElementUtil.java
sysml.library/Kernel Libraries/Kernel Semantic Library/Transfers.kerml
sysml.library/Systems Library/Flows.sysml
sysml/src/examples/Vehicle Example/SysML v2 Spec Annex A SimpleVehicleModel.sysml
sysml/src/training/13. Flows/Flow Definition Example.sysml
sysml/src/training/41. Language Extension/User Keyword Example.sysml
sysml/src/validation/14-Language Extensions/14c-Language Extensions.sysml
sysml/src/validation/17-Sequence Modeling/17b-Sequence-Modeling.sysml

This PR proactively fixes the following issues, even though resolutions for them have not yet been approved by the KerML 1.1 RTF or SysML 2.1 RTF:
- [KERML11-78](https://issues.omg.org/issues/KERML11-78) Transfers::transfers and Transfers::flowTransfers subset each other
- [SYSML21-324](https://issues.omg.org/issues/SYSML21-324) Flows::messages and Flows::flows subset each other
**Model Libraries**
_Kernel Semantic Library_
`Transfers`
- Made the features `transfers` and `messageTransfers` steps instead of flows. As a result, these features no longer have implied subsettings of `flowTransfers`.
_Systems Library_
`Flows`
- Removed the end features from the flow definition `Message` and the flow usage `messages`. As a result, `messages` no longer has an implied subsetting of `flows`.
- …

ST6RI-874 Features subset each other in Transfers and Flows library models (KERML11-78, SYSML21-324)

---

kerml/src/examples/Simple Tests/Redefinition.kerml
org.omg.kerml.xpect.tests/src/org/omg/kerml/xpect/tests/parsing/ParsingTests_Redefinition.kerml.xt
org.omg.kerml.xtext/src/org/omg/kerml/xtext/scoping/KerMLScope.xtend
sysml.library/Domain Libraries/Geometry/ShapeItems.sysml

This PR resolves an anomaly in the resolution of the name of a redefined feature due to certain forms of diamond specialization. This anomaly was because the name resolution algorithm (in `org.omg.kerml.xtext.scoping.KerMLScope`) traverses the specialization hierarchy without using  the derived property computation of inherited memberships, but it was not updated when the inherited membership computation was revised to handle multiply inherited redefinitions per the specification.
**Problem**
Consider the following KerML model:
```
classifier A {
feature f;
}
classifier B specializes A {
feature redefines f {
feature g;
}
}
classifier C specializes A, B {
feature subsets f {
feature redefines g; // ERROR: Couldn't resolve reference to Feature 'g'.
}
}
```
Previously, this model generated …

ST6RI-728 Name resolution of multiply inherited redefined features is not correct
